import { buildDomesticCatalog, type DomesticSpot } from "./spot-builder";

/** 人気・特徴的な国内スポット（都道府県代表・詳細データ以外） */
const SPOTS: DomesticSpot[] = [
  { prefecture: "北海道", name: "富良野", lat: 43.342, lon: 142.384, hook: "ラベンダーと、丘。", why: "夏の色が強い。", tags: "自然 高原 町" },
  { prefecture: "北海道", name: "知床", lat: 44.066, lon: 145.134, hook: "世界自然遺産の海。", why: "スケールが違う。", tags: "自然 世界遺産 海" },
  { prefecture: "北海道", name: "登別", lat: 42.412, lon: 141.106, hook: "地獄谷の湯気。", why: "札幌から、湯。", tags: "温泉 自然" },
  { prefecture: "青森", name: "津軽", lat: 40.824, lon: 140.406, hook: "りんごと、雪。", why: "弘前より、平野。", tags: "自然 町" },
  { prefecture: "山形", name: "山寺", lat: 38.312, lon: 140.437, hook: "1015段の階段。", why: "短時間で、非日常。", tags: "寺 山" },
  { prefecture: "福島", name: "裏磐梯", lat: 37.658, lon: 140.071, hook: "五色沼の池。", why: "猪苗代とセット。", tags: "湖 自然" },
  { prefecture: "栃木", name: "鬼怒川", lat: 36.822, lon: 139.709, hook: "渓谷沿いの温泉。", why: "日光の近く、湯。", tags: "温泉 渓谷" },
  { prefecture: "群馬", name: "四万", lat: 36.209, lon: 138.921, hook: "四万の湯。", why: "草津より、静か。", tags: "温泉 秘境" },
  { prefecture: "長野", name: "松本", lat: 36.238, lon: 137.972, hook: "黒い城。", why: "上高地の拠点。", tags: "城 街 歴史" },
  { prefecture: "岐阜", name: "下呂温泉", lat: 35.806, lon: 137.244, hook: "岐阜の名湯。", why: "高山と違う、湯。", tags: "温泉 休息" },
  { prefecture: "静岡", name: "修善寺", lat: 34.968, lon: 138.935, hook: "竹林と、温泉。", why: "伊豆の落ち着いた顔。", tags: "温泉 自然" },
  { prefecture: "愛知", name: "犬山", lat: 35.378, lon: 136.944, hook: "犬山城と、木曽川。", why: "名古屋から、城。", tags: "城 歴史" },
  { prefecture: "三重", name: "二見", lat: 34.483, lon: 136.789, hook: "伊勢神宮の入口。", why: "伊勢とセット。", tags: "神社 海" },
  { prefecture: "滋賀", name: "近江八幡", lat: 35.128, lon: 136.097, hook: "水郷と、旧道。", why: "琵琶湖の町。", tags: "古い町 水" },
  { prefecture: "京都", name: "宇治", lat: 34.884, lon: 135.799, hook: "抹茶と、平等院。", why: "京都の混雑を避ける。", tags: "寺 食べ歩き" },
  { prefecture: "大阪", name: "泉南", lat: 34.383, lon: 135.267, hook: "りんくうと、海。", why: "関西空港近く。", tags: "海 リゾート" },
  { prefecture: "兵庫", name: "姫路", lat: 34.839, lon: 134.693, hook: "白鷺城。", why: "日本の城の代表。", tags: "城 世界遺産 歴史" },
  { prefecture: "兵庫", name: "有馬温泉", lat: 34.794, lon: 135.251, hook: "金泉と、銀泉。", why: "神戸から、湯。", tags: "温泉 休息" },
  { prefecture: "奈良", name: "飞鸟", lat: 34.471, lon: 135.793, hook: "日本のはじまり。", why: "奈良より、深い歴史。", tags: "歴史 寺" },
  { prefecture: "和歌山", name: "熊野古道", lat: 33.84, lon: 135.774, hook: "世界遺産の道。", why: "歩く旅。", tags: "世界遺産 自然 歴史" },
  { prefecture: "鳥取", name: "水木しげるロード", lat: 35.539, lon: 133.231, hook: "妖怪の世界。", why: "境港と同エリア。", tags: "文化 街" },
  { prefecture: "島根", name: "松江", lat: 35.472, lon: 133.051, hook: "宍道湖と、城。", why: "出雲の隣。", tags: "湖 城" },
  { prefecture: "岡山", name: "津山", lat: 35.504, lon: 134.004, hook: "旧閑谷学校。", why: "岡山の山側。", tags: "歴史 町" },
  { prefecture: "広島", name: "鞆の浦", lat: 34.383, lon: 133.381, hook: "港町の残り。", why: "宮島と違う、港。", tags: "港 古い町 海" },
  { prefecture: "山口", name: "岩国", lat: 34.166, lon: 132.221, hook: "錦帯橋。", why: "下関とセット。", tags: "歴史 橋" },
  { prefecture: "香川", name: "豊島", lat: 34.477, lon: 134.075, hook: "直島より、静か。", why: "瀬戸内アート。", tags: "島 海 文化" },
  { prefecture: "香川", name: "父母ヶ浜", lat: 34.255, lon: 133.662, hook: "天空の鏡。", why: "夕方の海。", tags: "海 自然" },
  { prefecture: "愛媛", name: "今治", lat: 34.066, lon: 133.0, hook: "しまなみの入口。", why: "道後と違う、海。", tags: "海 橋" },
  { prefecture: "高知", name: "足折", lat: 32.931, lon: 132.508, hook: "太平洋の断崖。", why: "四万十より、海。", tags: "海 断崖 自然" },
  { prefecture: "福岡", name: "博多", lat: 33.59, lon: 130.401, hook: "ラーメンと、屋台。", why: "九州の玄関。", tags: "街 グルメ 食べ歩き" },
  { prefecture: "長崎", name: "平戸", lat: 33.368, lon: 129.553, hook: "オランダ商館。", why: "長崎より、港。", tags: "港 歴史" },
  { prefecture: "熊本", name: "人吉", lat: 32.211, lon: 130.755, hook: "球磨川の流れ。", why: "阿蘇と違う、川。", tags: "川 温泉 町" },
  { prefecture: "鹿児島", name: "奄美大島", lat: 28.377, lon: 129.493, hook: "サンゴの海。", why: "本島より、離島。", tags: "島 海 自然" },
  { prefecture: "沖縄", name: "与那国", lat: 24.467, lon: 122.986, hook: "日本最西端。", why: "最も遠い国内。", tags: "島 海 秘境" },
  { prefecture: "沖縄", name: "竹富島", lat: 24.325, lon: 123.945, hook: "星砂と、水牛車。", why: "石垣から、日帰り。", tags: "島 海 自然" },
  { prefecture: "東京", name: "小笠原", lat: 27.094, lon: 142.192, hook: "父島の青。", why: "最も遠い東京。", tags: "島 海 秘境" },
  { prefecture: "神奈川", name: "江の島", lat: 35.301, lon: 139.48, hook: "湘南の海。", why: "鎌倉とセット。", tags: "海 島" },
  { prefecture: "千葉", name: "南房総", lat: 34.977, lon: 139.952, hook: "海と、花。", why: "鴨川より、広い。", tags: "海 自然" },
  { prefecture: "石川", name: "能登", lat: 37.393, lon: 136.899, hook: "輪島の朝市。", why: "北陸の海。", tags: "海 市場 食べ歩き" },
  { prefecture: "福井", name: "永平寺", lat: 36.059, lon: 136.354, hook: "曹洞宗の大本山。", why: "禅と、静けさ。", tags: "寺 歴史 休息" },
  { prefecture: "北海道", name: "ニセコ", lat: 42.805, lon: 140.687, hook: "パウダースノー。", why: "冬の定番。", tags: "雪 山 自然" },
  { prefecture: "北海道", name: "帯広", lat: 42.924, lon: 143.196, hook: "十勝平野と、豚丼。", why: "札幌より、平野。", tags: "街 食べ歩き 自然" },
  { prefecture: "北海道", name: "網走", lat: 44.021, lon: 144.274, hook: "流氷と、監獄博物館。", why: "知床への入口。", tags: "海 自然 雪" },
  { prefecture: "北海道", name: "利尻島", lat: 45.172, lon: 141.227, hook: "利尻富士。", why: "最北の島。", tags: "島 山 自然" },
  { prefecture: "青森", name: "八戸", lat: 40.512, lon: 141.488, hook: "館鼻岸壁と、朝市。", why: "三陸の港。", tags: "港 海 食べ歩き" },
  { prefecture: "岩手", name: "雫石", lat: 39.696, lon: 140.976, hook: "小岩井農場と、高原。", why: "平泉の近く、自然。", tags: "自然 高原" },
  { prefecture: "宮城", name: "鳴子", lat: 38.749, lon: 140.732, hook: "こけしと、温泉。", why: "温泉郷の定番。", tags: "温泉 文化 町" },
  { prefecture: "秋田", name: "白神山地", lat: 40.45, lon: 140.25, hook: "世界自然遺産のブナ。", why: "自然の密度。", tags: "世界遺産 自然 山" },
  { prefecture: "山形", name: "鶴岡", lat: 38.727, lon: 139.826, hook: "羽黒山の入口。", why: "酒田とセット。", tags: "寺 自然" },
  { prefecture: "福島", name: "只見", lat: 37.349, lon: 139.875, hook: "第三セクターの景色。", why: "写真より、実際の緑。", tags: "自然 秘境 渓谷" },
  { prefecture: "茨城", name: "袋田", lat: 36.783, lon: 140.442, hook: "日本三大名瀑。", why: "大洗より、滝。", tags: "渓谷 自然" },
  { prefecture: "栃木", name: "益子", lat: 36.467, lon: 140.095, hook: "陶芸の町。", why: "日光より、工芸。", tags: "文化 町" },
  { prefecture: "群馬", name: "水上", lat: 36.778, lon: 138.968, hook: "谷川岳と、温泉。", why: "草津の近く、渓谷。", tags: "温泉 渓谷 山" },
  { prefecture: "千葉", name: "御宿", lat: 35.192, lon: 140.353, hook: "太平洋の岩礁。", why: "勝浦エリア、海。", tags: "海 リゾート" },
  { prefecture: "東京", name: "利島", lat: 34.529, lon: 139.256, hook: "伊豆七島のひとつ。", why: "日帰り圏の島。", tags: "島 海 自然" },
  { prefecture: "神奈川", name: "湯河原", lat: 35.149, lon: 139.107, hook: "万叶集の湯。", why: "箱根より、静か。", tags: "温泉 海 休息" },
  { prefecture: "神奈川", name: "三浦", lat: 35.144, lon: 139.618, hook: "三崎のまぐろ。", why: "鎌倉より、海。", tags: "海 食べ歩き" },
  { prefecture: "富山", name: "黒部峡谷", lat: 36.869, lon: 137.448, hook: "日本最深のV字谷。", why: "立山とセット。", tags: "渓谷 自然 秘境" },
  { prefecture: "石川", name: "和倉", lat: 36.894, lon: 136.934, hook: "能登の名湯。", why: "輪島より、湯。", tags: "温泉 海 休息" },
  { prefecture: "山梨", name: "清里", lat: 35.915, lon: 138.436, hook: "八ヶ岳の高原。", why: "河口湖より、高原。", tags: "高原 自然" },
  { prefecture: "長野", name: "安曇野", lat: 36.303, lon: 137.904, hook: "北アルプスの麓。", why: "松本の近く、平野。", tags: "自然 高原" },
  { prefecture: "岐阜", name: "恵那峡", lat: 35.449, lon: 137.412, hook: "舟下りと、渓谷。", why: "高山より、川。", tags: "渓谷 自然" },
  { prefecture: "静岡", name: "御前崎", lat: 34.623, lon: 138.131, hook: "太平洋の岬。", why: "熱海より、岬。", tags: "海 自然" },
  { prefecture: "静岡", name: "伊東", lat: 34.976, lon: 139.103, hook: "城ヶ崎と、温泉。", why: "伊豆の入口。", tags: "温泉 海" },
  { prefecture: "愛知", name: "常滑", lat: 34.886, lon: 136.832, hook: "焼き物と、空港。", why: "中部の玄関。", tags: "文化 海" },
  { prefecture: "三重", name: "桑名", lat: 35.062, lon: 136.684, hook: "なばなの里の近く。", why: "伊勢への途中。", tags: "町 自然" },
  { prefecture: "滋賀", name: "比叡山", lat: 35.067, lon: 135.84, hook: "延暦寺と、京都の裏。", why: "京都より、山。", tags: "寺 山 歴史" },
  { prefecture: "京都", name: "福知山", lat: 35.297, lon: 135.116, hook: "丹波の城下町。", why: "京都市外、北。", tags: "城 古い町" },
  { prefecture: "兵庫", name: "明石", lat: 34.643, lon: 134.997, hook: "明石海峡と、たこ。", why: "神戸より、海。", tags: "海 食べ歩き" },
  { prefecture: "奈良", name: "明日香", lat: 34.471, lon: 135.793, hook: "飛鳥の続き。", why: "古墳と、田。", tags: "歴史 自然" },
  { prefecture: "和歌山", name: "那智勝浦", lat: 33.626, lon: 135.941, hook: "マグロと、那智の滝。", why: "白浜の隣。", tags: "海 食べ歩き 自然" },
  { prefecture: "鳥取", name: "三朝", lat: 35.409, lon: 133.898, hook: "ラジウム泉の湯。", why: "砂丘より、湯。", tags: "温泉 休息" },
  { prefecture: "島根", name: "隠岐", lat: 36.207, lon: 133.319, hook: "島根の離島。", why: "出雲より、海。", tags: "島 海 自然" },
  { prefecture: "岡山", name: "真庭", lat: 35.078, lon: 133.691, hook: "蒜山高原の近く。", why: "岡山の山側。", tags: "高原 自然" },
  { prefecture: "広島", name: "因島", lat: 34.284, lon: 133.181, hook: "しまなみの島。", why: "尾道とセット。", tags: "島 海 橋" },
  { prefecture: "山口", name: "秋吉台", lat: 34.252, lon: 131.307, hook: "カルスト台地。", why: "萩より、自然。", tags: "自然 高原" },
  { prefecture: "徳島", name: "阿南", lat: 33.918, lon: 134.662, hook: "南の海。", why: "鳴門より、海。", tags: "海 自然" },
  { prefecture: "香川", name: "丸亀", lat: 34.289, lon: 133.797, hook: "金刀比羅の近く。", why: "琴平への入口。", tags: "城 海" },
  { prefecture: "高知", name: "安芸", lat: 33.502, lon: 133.907, hook: "土佐湾の港。", why: "四万十より、港。", tags: "港 海" },
  { prefecture: "福岡", name: "北九州", lat: 33.886, lon: 130.883, hook: "門司港と、海峡。", why: "博多より、港。", tags: "港 歴史 夜景" },
  { prefecture: "佐賀", name: "武雄", lat: 33.196, lon: 130.019, hook: "武雄温泉と、図書館。", why: "嬉野とセット。", tags: "温泉 文化" },
  { prefecture: "長崎", name: "壱岐", lat: 33.785, lon: 129.701, hook: "離島の酒と、海。", why: "長崎より、島。", tags: "島 海 食べ歩き" },
  { prefecture: "熊本", name: "三角", lat: 32.608, lon: 130.467, hook: "天草への渡し。", why: "阿蘇より、海。", tags: "海 港" },
  { prefecture: "宮崎", name: "西都", lat: 32.11, lon: 131.402, hook: "原尻の滝。", why: "高千穂より、滝。", tags: "渓谷 自然" },
  { prefecture: "沖縄", name: "石垣", lat: 24.341, lon: 124.155, hook: "八重山の中心。", why: "那覇より、離島。", tags: "島 海 リゾート" },
  { prefecture: "北海道", name: "支笏湖", lat: 42.757, lon: 141.328, hook: "透明度の高い湖。", why: "ニセコより、湖。", tags: "湖 自然" },
  { prefecture: "北海道", name: "旭川", lat: 43.771, lon: 142.365, hook: "動物園と、ラーメン。", why: "札幌より、北。", tags: "街 自然" },
  { prefecture: "岩手", name: "気仙沼", lat: 38.909, lon: 141.569, hook: "三陸の海。", why: "久慈と同じ海岸。", tags: "海 自然" },
  { prefecture: "宮城", name: "登米", lat: 38.691, lon: 141.187, hook: "旧舎館。", why: "松島より、田園。", tags: "歴史 町" },
  { prefecture: "福島", name: "喜多方", lat: 37.651, lon: 139.874, hook: "ラーメンと、蔵。", why: "会津より、食。", tags: "食べ歩き 古い町" },
  { prefecture: "茨城", name: "牛久", lat: 36.029, lon: 140.15, hook: "大仏と、霞ヶ浦。", why: "大洗より、湖。", tags: "寺 湖" },
  { prefecture: "栃木", name: "茂木", lat: 36.533, lon: 140.188, hook: "いちごと、町。", why: "日光より、田園。", tags: "自然 町" },
  { prefecture: "群馬", name: "老神", lat: 36.612, lon: 138.947, hook: "吾妻川の温泉。", why: "草津より、渓谷。", tags: "温泉 渓谷" },
  { prefecture: "埼玉", name: "深谷", lat: 36.197, lon: 139.281, hook: "うなぎの町。", why: "秩父より、食。", tags: "食べ歩き 町" },
  { prefecture: "千葉", name: "木更津", lat: 35.381, lon: 139.917, hook: "東京湾の海。", why: "鴨川より、湾。", tags: "海 自然" },
  { prefecture: "東京", name: "八丈島", lat: 33.109, lon: 139.789, hook: "東京の南の島。", why: "伊豆大島より、遠い。", tags: "島 海 自然" },
  { prefecture: "神奈川", name: "小田原", lat: 35.256, lon: 139.154, hook: "城と、箱根の入口。", why: "鎌倉より、城。", tags: "城 海 歴史" },
  { prefecture: "新潟", name: "長岡", lat: 37.446, lon: 138.851, hook: "信濃川と、花火。", why: "越後湯沢より、街。", tags: "街 川" },
  { prefecture: "富山", name: "高岡", lat: 36.754, lon: 137.025, hook: "万葉の里。", why: "立山より、平野。", tags: "文化 歴史" },
  { prefecture: "石川", name: "山中", lat: 36.215, lon: 136.903, hook: "山中温泉。", why: "金沢より、湯。", tags: "温泉 休息" },
  { prefecture: "福井", name: "三方五湖", lat: 35.592, lon: 135.898, hook: "ラムサールの湿地。", why: "東尋坊より、湖。", tags: "湖 自然" },
  { prefecture: "山梨", name: "身延", lat: 35.378, lon: 138.425, hook: "日蓮聖地。", why: "河口湖より、山。", tags: "寺 山 歴史" },
  { prefecture: "長野", name: "茅野", lat: 35.996, lon: 138.158, hook: "八ヶ岳の麓。", why: "軽井沢より、湖。", tags: "湖 高原 自然" },
  { prefecture: "岐阜", name: "関", lat: 35.496, lon: 136.918, hook: "長良川。", why: "白川郷より、川。", tags: "川 自然" },
  { prefecture: "静岡", name: "袋井", lat: 34.75, lon: 137.925, hook: "可睡斎と、茶。", why: "浜松より、静けさ。", tags: "寺 自然" },
  { prefecture: "愛知", name: "渥美", lat: 34.637, lon: 137.162, hook: "三河湾の半島。", why: "名古屋より、海。", tags: "海 自然" },
  { prefecture: "三重", name: "松阪", lat: 34.578, lon: 136.527, hook: "牛と、城。", why: "伊勢より、食。", tags: "城 食べ歩き" },
  { prefecture: "滋賀", name: "草津", lat: 35.017, lon: 135.968, hook: "宿場町。", why: "彦根より、歴史。", tags: "古い町 歴史" },
  { prefecture: "京都", name: "宮津", lat: 35.535, lon: 135.195, hook: "天橋立の町。", why: "天橋立の拠点。", tags: "海 自然" },
  { prefecture: "大阪", name: "交野", lat: 34.787, lon: 135.678, hook: "星のブランコ。", why: "大阪の奥、自然。", tags: "自然 山" },
  { prefecture: "兵庫", name: "香住", lat: 35.648, lon: 134.598, hook: "但馬の蟹。", why: "神戸より、海。", tags: "海 食べ歩き" },
  { prefecture: "奈良", name: "五條", lat: 34.352, lon: 135.697, hook: "吉野の入口。", why: "吉野より、町。", tags: "町 歴史" },
  { prefecture: "和歌山", name: "白川", lat: 33.935, lon: 135.165, hook: "みなべの梅。", why: "田辺より、自然。", tags: "自然" },
  { prefecture: "鳥取", name: "米子", lat: 35.428, lon: 133.331, hook: "大山の近く。", why: "砂丘より、街。", tags: "街 山" },
  { prefecture: "島根", name: "大田", lat: 35.192, lon: 132.499, hook: "石見銀山の近く。", why: "出雲より、歴史。", tags: "歴史 自然" },
  { prefecture: "岡山", name: "井原", lat: 34.628, lon: 133.615, hook: "平野の町。", why: "岡山より、田園。", tags: "町 自然" },
  { prefecture: "広島", name: "庄原", lat: 34.861, lon: 133.017, hook: "芸北の入口。", why: "三次より、山。", tags: "自然 町" },
  { prefecture: "山口", name: "宇部", lat: 33.951, lon: 131.247, hook: "洞海と、炭。", why: "下関より、海。", tags: "海 自然" },
  { prefecture: "徳島", name: "小松島", lat: 34.0, lon: 134.59, hook: "阿波踊り。", why: "鳴門より、文化。", tags: "文化 海" },
  { prefecture: "香川", name: "坂出", lat: 34.316, lon: 133.86, hook: "瀬戸大橋。", why: "高松より、橋。", tags: "海 橋" },
  { prefecture: "愛媛", name: "八幡浜", lat: 33.462, lon: 132.423, hook: "宇和海。", why: "宇和島より、港。", tags: "港 海" },
  { prefecture: "高知", name: "中村", lat: 32.996, lon: 132.934, hook: "四万十の終点。", why: "四万十川の出口。", tags: "川 海 自然" },
  { prefecture: "福岡", name: "直方", lat: 33.746, lon: 130.729, hook: "炭坑節。", why: "北九州より、歴史。", tags: "歴史 文化" },
  { prefecture: "佐賀", name: "伊万里湾", lat: 33.265, lon: 129.88, hook: "牡蠣と、海。", why: "有田より、海。", tags: "海 食べ歩き" },
  { prefecture: "長崎", name: "島原", lat: 32.789, lon: 130.367, hook: "温泉と、城。", why: "雲仙より、湯。", tags: "温泉 城" },
  { prefecture: "熊本", name: "水俣", lat: 32.212, lon: 130.408, hook: "不知火海峡。", why: "八代より、海。", tags: "海 自然" },
  { prefecture: "大分", name: "杵築", lat: 33.279, lon: 131.851, hook: "城下の温泉。", why: "別府より、静か。", tags: "温泉 城" },
  { prefecture: "宮崎", name: "都城", lat: 31.721, lon: 131.068, hook: "都城盆地。", why: "青島より、平野。", tags: "自然 町" },
  { prefecture: "鹿児島", name: "川内", lat: 31.813, lon: 130.309, hook: "薩摩の町。", why: "鹿児島より、北。", tags: "町 歴史" },
  { prefecture: "沖縄", name: "恩納", lat: 26.497, lon: 127.853, hook: "西海岸のリゾート。", why: "那覇より、海。", tags: "海 リゾート" },
  { prefecture: "北海道", name: "稚内", lat: 45.415, lon: 141.673, hook: "日本最北の街。", why: "利尻より、港。", tags: "海 自然" },
  { prefecture: "北海道", name: "留萌", lat: 43.944, lon: 141.637, hook: "オロロンライン。", why: "富良野より、海。", tags: "海 自然" },
  { prefecture: "青森", name: "西津軽", lat: 40.813, lon: 140.047, hook: "津軽半島の西。", why: "弘前より、海。", tags: "海 自然" },
  { prefecture: "岩手", name: "釜石", lat: 39.273, lon: 141.885, hook: "三陸の港。", why: "久慈より、南。", tags: "港 海" },
  { prefecture: "宮城", name: "石巻", lat: 38.434, lon: 141.303, hook: "牡鹿半島の入口。", why: "松島より、港。", tags: "港 海" },
  { prefecture: "秋田", name: "角館", lat: 39.6, lon: 140.562, hook: "武家屋敷の並木。", why: "詳細データと別名。", tags: "古い町 歴史" },
  { prefecture: "山形", name: "新庄", lat: 38.765, lon: 140.302, hook: "最上川の町。", why: "银山温泉より、奥。", tags: "川 町" },
  { prefecture: "福島", name: "磐梯", lat: 37.556, lon: 140.031, hook: "猪苗代の隣。", why: "会津より、湖。", tags: "湖 山 自然" },
  { prefecture: "茨城", name: "日立", lat: 36.599, lon: 140.651, hook: "海と、工場の夜景。", why: "大洗より、北。", tags: "海 夜景" },
  { prefecture: "栃木", name: "塩原", lat: 36.966, lon: 139.563, hook: "11湯の温泉郷。", why: "那須より、湯。", tags: "温泉 渓谷" },
  { prefecture: "群馬", name: "月夜野", lat: 36.683, lon: 138.933, hook: "渋川の近く、渓谷。", why: "伊香保より、自然。", tags: "渓谷 自然" },
  { prefecture: "埼玉", name: "長瀞", lat: 36.097, lon: 139.115, hook: "岩畳の川。", why: "秩父の近く。", tags: "川 渓谷" },
  { prefecture: "千葉", name: "富津", lat: 35.304, lon: 139.857, hook: "東京湾の絶景。", why: "木更津より、海。", tags: "海 自然" },
  { prefecture: "東京", name: "三宅島", lat: 34.077, lon: 139.404, hook: "火山島。", why: "伊豆大島の隣。", tags: "島 火山 海" },
  { prefecture: "神奈川", name: "真鶴", lat: 35.157, lon: 139.137, hook: "相模湾の岬。", why: "湯河原より、海。", tags: "海 自然" },
  { prefecture: "新潟", name: "湯沢", lat: 36.936, lon: 138.812, hook: "雪と、温泉。", why: "越後湯沢の別名。", tags: "温泉 雪" },
  { prefecture: "富山", name: "射水", lat: 36.766, lon: 137.078, hook: "新湊の港。", why: "氷見より、港。", tags: "港 海" },
  { prefecture: "石川", name: "穴水", lat: 37.025, lon: 136.965, hook: "能登の奥。", why: "輪島より、西。", tags: "海 自然" },
  { prefecture: "福井", name: "勝山", lat: 36.065, lon: 136.501, hook: "恐竜の里。", why: "永平寺より、平野。", tags: "文化 自然" },
  { prefecture: "山梨", name: "大月", lat: 35.608, lon: 138.939, hook: "桂川の渓谷。", why: "富士吉田より、川。", tags: "渓谷 自然" },
  { prefecture: "長野", name: "大町", lat: 36.503, lon: 137.852, hook: "北アルプスの玄関。", why: "白馬より、湖。", tags: "湖 山 自然" },
  { prefecture: "岐阜", name: "飛騨", lat: 36.238, lon: 137.186, hook: "古い町並み。", why: "高山の近く。", tags: "古い町 歴史" },
  { prefecture: "静岡", name: "下田", lat: 34.679, lon: 138.945, hook: "黒船と、海。", why: "南伊豆の入口。", tags: "海 歴史" },
  { prefecture: "愛知", name: "知多", lat: 34.883, lon: 136.937, hook: "半島の海。", why: "名古屋より、南。", tags: "海 自然" },
  { prefecture: "三重", name: "御浜", lat: 33.828, lon: 136.021, hook: "熊野の海。", why: "熊野と同エリア。", tags: "海 自然" },
  { prefecture: "滋賀", name: "高島", lat: 35.352, lon: 136.033, hook: "湖北の自然。", why: "琵琶湖より、静か。", tags: "湖 自然" },
  { prefecture: "京都", name: "伊根", lat: 35.675, lon: 135.272, hook: "舟屋の町。", why: "天橋立より、港。", tags: "港 古い町 海" },
  { prefecture: "大阪", name: "河内長野", lat: 34.458, lon: 135.564, hook: "大阪の里山。", why: "交野より、自然。", tags: "自然 町" },
  { prefecture: "兵庫", name: "竹野", lat: 35.675, lon: 134.823, hook: "但馬の海。", why: "豊岡より、海岸。", tags: "海 自然" },
  { prefecture: "奈良", name: "天理", lat: 34.596, lon: 135.793, hook: "古の都。", why: "奈良より、宗教。", tags: "歴史 神社" },
  { prefecture: "和歌山", name: "御坊", lat: 33.891, lon: 135.152, hook: "日高の中心。", why: "白浜より、平野。", tags: "町 海" },
  { prefecture: "鳥取", name: "智頭", lat: 35.265, lon: 134.226, hook: "高原の駅。", why: "大山より、高原。", tags: "高原 自然" },
  { prefecture: "島根", name: "江津", lat: 35.011, lon: 132.22, hook: "山陰の港。", why: "益田より、東。", tags: "港 海" },
  { prefecture: "岡山", name: "美作", lat: 35.011, lon: 134.148, hook: "岡山の山側。", why: "蒜山より、平野。", tags: "自然 町" },
  { prefecture: "広島", name: "江田島", lat: 34.256, lon: 132.479, hook: "瀬戸内の島。", why: "呉より、島。", tags: "島 海" },
  { prefecture: "山口", name: "光", lat: 33.971, lon: 131.941, hook: "室積の港。", why: "下関より、東。", tags: "港 海" },
  { prefecture: "徳島", name: "海陽", lat: 33.606, lon: 134.375, hook: "南海の断崖。", why: "阿南より、海。", tags: "海 断崖 自然" },
  { prefecture: "香川", name: "直島", lat: 34.46, lon: 133.995, hook: "アートの島。", why: "詳細データと別名。", tags: "島 海 文化" },
  { prefecture: "愛媛", name: "内子", lat: 33.756, lon: 132.655, hook: "木造の町。", why: "道後より、静か。", tags: "古い町 歴史" },
  { prefecture: "高知", name: "土佐清水", lat: 32.781, lon: 132.955, hook: "足折の近く。", why: "四万十より、南。", tags: "海 自然" },
  { prefecture: "福岡", name: "秋月", lat: 33.471, lon: 130.931, hook: "小京都。", why: "太宰府より、城。", tags: "城 歴史" },
  { prefecture: "佐賀", name: "多久", lat: 33.288, lon: 130.107, hook: "温泉と、陶。", why: "伊万里より、湯。", tags: "温泉 文化" },
  { prefecture: "長崎", name: "厳原", lat: 34.203, lon: 129.287, hook: "対馬の港。", why: "対馬の中心。", tags: "港 海" },
  { prefecture: "熊本", name: "山都", lat: 32.984, lon: 131.152, hook: "阿蘇の西。", why: "阿蘇より、渓谷。", tags: "渓谷 自然" },
  { prefecture: "大分", name: "玖珠", lat: 33.279, lon: 131.251, hook: "日田の隣。", why: "由布院より、山。", tags: "自然 町" },
  { prefecture: "宮崎", name: "日向", lat: 32.422, lon: 131.624, hook: "日向灘。", why: "延岡より、海。", tags: "海 自然" },
  { prefecture: "鹿児島", name: "徳之島", lat: 27.802, lon: 129.018, hook: "奄美の南端。", why: "奄美より、離島。", tags: "島 海 自然" },
  { prefecture: "沖縄", name: "久米島", lat: 26.341, lon: 126.801, hook: "島時間。", why: "那覇より、離島。", tags: "島 海 リゾート" },
];

export const domesticExtraDestinations = buildDomesticCatalog(SPOTS, "dom");
