import type { DayPlan, Traits, TransportLeg } from "./types";
import type { Destination } from "./destinations";
import { buildSpotLinks } from "./spot-links";

type IntlInput = {
  id: string;
  name: string;
  country: string;
  city: string;
  hook: string;
  why: string;
  weights: Traits;
  dailyMin: number;
  dailyMax: number;
  minDays: number;
  maxDays: number;
  flightHours: string;
  airport: string;
  groundNote: string;
  plan: DayPlan[];
};

function flightLegs(airport: string, city: string, flightHours: string, groundNote: string) {
  const legs: TransportLeg[] = [
    {
      from: "羽田 or 成田",
      to: airport,
      mode: "flight",
      duration: flightHours,
      note: "直行便を優先。乗継は最低2時間見る",
    },
    {
      from: airport,
      to: city,
      mode: "train",
      duration: "約30–90分",
      transfer: true,
      note: groundNote,
    },
  ];
  return {
    summary: "海外は空路が本体。到着日は移動だけで終わってもいい。",
    legs,
  };
}

function intl(input: IntlInput): Destination {
  const transport = flightLegs(input.airport, input.city, input.flightHours, input.groundNote);
  return {
    id: input.id,
    name: input.name,
    region: `${input.country} · ${input.city}`,
    country: input.country,
    links: buildSpotLinks({
      name: input.name,
      region: input.city,
      country: input.country,
    }),
    hook: input.hook,
    why: input.why,
    weights: input.weights,
    dailyMin: input.dailyMin,
    dailyMax: input.dailyMax,
    minDays: input.minDays,
    maxDays: input.maxDays,
    access: { 東京: transport, 大阪: transport, 名古屋: transport, 福岡: transport },
    plan: input.plan,
    extraDays: [
      {
        day: input.plan.length + 1,
        title: "余白の日",
        beats: [
          {
            time: "終日",
            place: input.city,
            detail: "予定を足さない。昨日の街並みにもう一度入る。",
          },
        ],
      },
    ],
  };
}

export const overseasDestinations: Destination[] = [
  intl({
    id: "seoul",
    name: "ソウル",
    country: "韓国",
    city: "ソウル",
    hook: "近いのに言語も食も全部違う。週末で空気が変わる。",
    why: "海外に行きたいけど、長期休暇は取れない人向け。",
    weights: { solitude: 0.45, novelty: 0.72, slow: 0.48, nature: 0.25, comfort: 0.68, food: 0.88, rest: 0.42, culture: 0.62 },
    dailyMin: 22000,
    dailyMax: 42000,
    minDays: 2,
    maxDays: 4,
    flightHours: "約2時間30分",
    airport: "仁川 (ICN)",
    groundNote: "AREX または 空港リムジン",
    plan: [
      { day: 1, title: "到着して弘大だけ", beats: [{ time: "夕方", place: "弘大", detail: "荷物を置いたら一軒だけ。夜の街の音を聞く。" }] },
      { day: 2, title: "北村と食べ歩き", beats: [{ time: "午前", place: "北村韓屋村", detail: "早い時間。混む前に歩く。" }, { time: "午後", place: "広蔵市場", detail: "食べる場所は一つに決める。" }] },
    ],
  }),
  intl({
    id: "taipei",
    name: "台北",
    country: "台湾",
    city: "台北",
    hook: "小籠包より先に、湿度と夜市の音が来る。",
    why: "食と散歩が好きで、近場の海外から始めたい人。",
    weights: { solitude: 0.5, novelty: 0.68, slow: 0.55, nature: 0.35, comfort: 0.65, food: 0.92, rest: 0.45, culture: 0.58 },
    dailyMin: 20000,
    dailyMax: 38000,
    minDays: 2,
    maxDays: 5,
    flightHours: "約3時間30分",
    airport: "桃園 (TPE)",
    groundNote: "MRT または 空港バスで市内へ",
    plan: [
      { day: 1, title: "迪化街と河岸", beats: [{ time: "午後", place: "大稻埕", detail: "夕方から。河と旧市街を短く。" }] },
      { day: 2, title: "九份は半日", beats: [{ time: "午前", place: "九份", detail: "日帰り。夜まで延ばさない。" }, { time: "夜", place: "寧夏夜市", detail: "一軒決めて回らない。" }] },
    ],
  }),
  intl({
    id: "bangkok",
    name: "バンコク",
    country: "タイ",
    city: "バンコク",
    hook: "暑さと香りと、寺の静けさが同じ日に来る。",
    why: "刺激と食と、少しの混乱が欲しい人。",
    weights: { solitude: 0.42, novelty: 0.85, slow: 0.4, nature: 0.3, comfort: 0.55, food: 0.95, rest: 0.35, culture: 0.72 },
    dailyMin: 18000,
    dailyMax: 35000,
    minDays: 3,
    maxDays: 6,
    flightHours: "約6時間30分",
    airport: "スワンナプーム (BKK)",
    groundNote: "BTS/MRT または 空港レールリンク",
    plan: [
      { day: 1, title: "着いて川沿い", beats: [{ time: "夕方", place: "チャオプラヤー川", detail: "初日は船に乗らなくていい。川を見るだけ。" }] },
      { day: 2, title: "寺は一つ", beats: [{ time: "午前", place: "ワット・ポー", detail: "早い時間。全部回らない。" }, { time: "夜", place: "屋台", detail: "一皿で満足する。" }] },
    ],
  }),
  intl({
    id: "bali",
    name: "バリ",
    country: "インドネシア",
    city: "ウブド",
    hook: "リゾートというより、湿度と田んぼの朝。",
    why: "休息と自然を、国内より遠くで欲しい人。",
    weights: { solitude: 0.62, novelty: 0.78, slow: 0.88, nature: 0.85, comfort: 0.72, food: 0.55, rest: 0.9, culture: 0.55 },
    dailyMin: 22000,
    dailyMax: 45000,
    minDays: 4,
    maxDays: 8,
    flightHours: "約7時間",
    airport: "デンパサール (DPS)",
    groundNote: "ウブドまでは車。移動は1日1回まで",
    plan: [
      { day: 1, title: "ウブドに落ちる", beats: [{ time: "午後", place: "ウブド", detail: "テガララン棚田は翌日。初日は町の中心だけ。" }] },
      { day: 2, title: "棚田とカフェ", beats: [{ time: "朝", place: "テガララン", detail: "朝一。昼前に戻る。" }, { time: "午後", place: "カフェ", detail: "予定を足さない。" }] },
    ],
  }),
  intl({
    id: "singapore",
    name: "シンガポール",
    country: "シンガポール",
    city: "シンガポール",
    hook: "整っていて、それでも南国の夜がある。",
    why: "言語の不安が少なく、初めての海外に近い。",
    weights: { solitude: 0.48, novelty: 0.65, slow: 0.52, nature: 0.42, comfort: 0.85, food: 0.82, rest: 0.5, culture: 0.55 },
    dailyMin: 28000,
    dailyMax: 52000,
    minDays: 3,
    maxDays: 5,
    flightHours: "約7時間",
    airport: "チャンギ (SIN)",
    groundNote: "MRT で市内へ。タクシーは初日だけでも可",
    plan: [
      { day: 1, title: "ホーカー一軒", beats: [{ time: "夜", place: "マックスウェル", detail: "一皿決めて、あとは歩く。" }] },
      { day: 2, title: "ガーデンズと川", beats: [{ time: "午前", place: "ガーデンズ・バイ・ザ・ベイ", detail: "屋外だけでもいい。" }, { time: "夕方", place: "クラークキー", detail: "夜景は短く。" }] },
    ],
  }),
  intl({
    id: "hanoi",
    name: "ハノイ",
    country: "ベトナム",
    city: "ハノイ",
    hook: "バイクの音とコーヒー。予定表より街の速度に合わせる。",
    why: "活気と食が欲しく、少しのカオスも許容できる人。",
    weights: { solitude: 0.4, novelty: 0.88, slow: 0.45, nature: 0.28, comfort: 0.45, food: 0.9, rest: 0.35, culture: 0.68 },
    dailyMin: 16000,
    dailyMax: 32000,
    minDays: 3,
    maxDays: 6,
    flightHours: "約5時間30分",
    airport: "ノイバイ (HAN)",
    groundNote: "Grab または 空港バス",
    plan: [
      { day: 1, title: "旧市街の一辺", beats: [{ time: "午後", place: "36古街", detail: "一方向だけ歩く。" }] },
      { day: 2, title: "湖とコーヒー", beats: [{ time: "朝", place: "ホアンキエム湖", detail: "人が増える前。" }, { time: "午後", place: "カフェ", detail: "卵コーヒーは一軒。" }] },
    ],
  }),
  intl({
    id: "hongkong",
    name: "香港",
    country: "中国香港",
    city: "香港",
    hook: "高層と路地、同じ15分で行き来できる。",
    why: "食べ歩きと夜景が好きで、移動が短い旅がいい人。",
    weights: { solitude: 0.38, novelty: 0.7, slow: 0.42, nature: 0.22, comfort: 0.75, food: 0.9, rest: 0.38, culture: 0.6 },
    dailyMin: 26000,
    dailyMax: 48000,
    minDays: 2,
    maxDays: 4,
    flightHours: "約4時間30分",
    airport: "香港 (HKG)",
    groundNote: "Airport Express で九龍/香港駅",
    plan: [
      { day: 1, title: "中環の坂", beats: [{ time: "午後", place: "セントラル", detail: "エスカレーターは途中で降りる。" }] },
      { day: 2, title: "点心と夜景", beats: [{ time: "朝", place: "点心", detail: "一軒決める。" }, { time: "夜", place: "ビクトリアピーク", detail: "行列が長ければ諦めていい。" }] },
    ],
  }),
  intl({
    id: "paris",
    name: "パリ",
    country: "フランス",
    city: "パリ",
    hook: "美術館より、川沿いのベンチ。",
    why: "文化より「生活のリズムが変わる」感覚が欲しい人。",
    weights: { solitude: 0.55, novelty: 0.82, slow: 0.75, nature: 0.3, comfort: 0.7, food: 0.78, rest: 0.55, culture: 0.92 },
    dailyMin: 35000,
    dailyMax: 75000,
    minDays: 4,
    maxDays: 8,
    flightHours: "約12時間",
    airport: "CDG",
    groundNote: "RER B で市内。初日は移動だけ",
    plan: [
      { day: 1, title: "マレ散歩", beats: [{ time: "午後", place: "マレ地区", detail: "美術館は一つだけ。" }] },
      { day: 2, title: "セーヌの一日", beats: [{ time: "終日", place: "セーヌ川", detail: "歩く。橋を渡る。座る。" }] },
    ],
  }),
  intl({
    id: "lisbon",
    name: "リスボン",
    country: "ポルトガル",
    city: "リスボン",
    hook: "坂とタイルと、大西洋の光。",
    why: "欧州だけど、緊張感より余白が先に来る人。",
    weights: { solitude: 0.58, novelty: 0.8, slow: 0.78, nature: 0.45, comfort: 0.62, food: 0.72, rest: 0.62, culture: 0.78 },
    dailyMin: 30000,
    dailyMax: 58000,
    minDays: 4,
    maxDays: 7,
    flightHours: "約14時間",
    airport: "LIS",
    groundNote: "メトロまたは Uber",
    plan: [
      { day: 1, title: "アルファマ", beats: [{ time: "午後", place: "アルファマ", detail: "28番トラムは短く。" }] },
      { day: 2, title: "ベレン", beats: [{ time: "午前", place: "ベレンの塔", detail: "外から見るだけでもいい。" }] },
    ],
  }),
  intl({
    id: "reykjavik",
    name: "レイキャビク",
    country: "アイスランド",
    city: "レイキャビク",
    hook: "白夜か極夜。天気が計画より強い。",
    why: "自然が主役で、街は拠点にすればいい人。",
    weights: { solitude: 0.72, novelty: 0.95, slow: 0.65, nature: 0.98, comfort: 0.55, food: 0.45, rest: 0.5, culture: 0.4 },
    dailyMin: 45000,
    dailyMax: 90000,
    minDays: 5,
    maxDays: 9,
    flightHours: "約13時間",
    airport: "KEF",
    groundNote: "Flybus で市内。レンタカーは日数がある人だけ",
    plan: [
      { day: 1, title: "街で整える", beats: [{ time: "午後", place: "ハルグラムスキルキャ", detail: "外から。初日は近場。" }] },
      { day: 2, title: "ゴールデンサークル", beats: [{ time: "終日", place: "シンクヴェトルリル", detail: "日帰り。天候で中止も可。" }] },
    ],
  }),
  intl({
    id: "rome",
    name: "ローマ",
    country: "イタリア",
    city: "ローマ",
    hook: "遺跡と路地裏の食。歩くほど時間が足りない。",
    why: "歴史と食を、少し雑に楽しみたい人。",
    weights: { solitude: 0.45, novelty: 0.75, slow: 0.5, nature: 0.25, comfort: 0.6, food: 0.92, rest: 0.4, culture: 0.95 },
    dailyMin: 32000,
    dailyMax: 65000,
    minDays: 4,
    maxDays: 7,
    flightHours: "約12時間30分",
    airport: "FCO",
    groundNote: "Leonardo Express または タクシー定額",
    plan: [
      { day: 1, title: "トラステヴェレ", beats: [{ time: "夕方", place: "トラステヴェレ", detail: "初日は夜の街だけ。" }] },
      { day: 2, title: "遺跡は一つ", beats: [{ time: "午前", place: "コロッセオ", detail: "予約枠に合わせる。他は足さない。" }] },
    ],
  }),
  intl({
    id: "honolulu",
    name: "ホノルル",
    country: "アメリカ（ハワイ）",
    city: "ホノルル",
    hook: "日本から近い海外。海が先に来る。",
    why: "パスポートは欲しいけど、長時間フライトは避けたい人。",
    weights: { solitude: 0.5, novelty: 0.6, slow: 0.82, nature: 0.88, comfort: 0.78, food: 0.55, rest: 0.88, culture: 0.35 },
    dailyMin: 35000,
    dailyMax: 70000,
    minDays: 4,
    maxDays: 8,
    flightHours: "約7時間30分",
    airport: "ホノルル (HNL)",
    groundNote: "TheBus または ウber",
    plan: [
      { day: 1, title: "ワイキキの夕方", beats: [{ time: "夕方", place: "ワイキキ", detail: "泳がなくていい。砂浜に座る。" }] },
      { day: 2, title: "北岸は半日", beats: [{ time: "午前", place: "ノースショア", detail: "日帰り。帰りは早め。" }] },
    ],
  }),
  intl({
    id: "nyc",
    name: "ニューヨーク",
    country: "アメリカ",
    city: "ニューヨーク",
    hook: "歩いても歩いても、同じ街がない。",
    why: "刺激と文化と、少しの疲れすら楽しめる人。",
    weights: { solitude: 0.35, novelty: 0.88, slow: 0.38, nature: 0.2, comfort: 0.65, food: 0.85, rest: 0.3, culture: 0.88 },
    dailyMin: 40000,
    dailyMax: 85000,
    minDays: 4,
    maxDays: 8,
    flightHours: "約12時間",
    airport: "JFK/EWR",
    groundNote: "AirTrain + 地下鉄。初日は移動のみでも可",
    plan: [
      { day: 1, title: "ブルックリン橋", beats: [{ time: "夕方", place: "DUMBO", detail: "橋を渡る。写真より風。" }] },
      { day: 2, title: "美術館一つ", beats: [{ time: "午前", place: "MoMA or メト", detail: "全部は無理。一館。" }] },
    ],
  }),
  intl({
    id: "vancouver",
    name: "バンクーバー",
    country: "カナダ",
    city: "バンクーバー",
    hook: "海と山が同じ都市にある。",
    why: "自然と街の両方が欲しく、英語圏が不安でない人。",
    weights: { solitude: 0.55, novelty: 0.72, slow: 0.62, nature: 0.85, comfort: 0.72, food: 0.65, rest: 0.58, culture: 0.5 },
    dailyMin: 32000,
    dailyMax: 62000,
    minDays: 4,
    maxDays: 8,
    flightHours: "約9時間30分",
    airport: "YVR",
    groundNote: "Canada Line で市内",
    plan: [
      { day: 1, title: "スタンレーパーク", beats: [{ time: "午後", place: "スタンレーパーク", detail: "一周しない。入り口だけ。" }] },
      { day: 2, title: "グランビル島", beats: [{ time: "午前", place: "グランビル島", detail: "市場で昼。" }] },
    ],
  }),
  intl({
    id: "queenstown",
    name: "クイーンズタウン",
    country: "ニュージーランド",
    city: "クイーンズタウン",
    hook: "湖と山。アクティビティより、座って見る。",
    why: "遠いけど、景色で全部回収したい人。",
    weights: { solitude: 0.65, novelty: 0.9, slow: 0.7, nature: 0.95, comfort: 0.6, food: 0.5, rest: 0.55, culture: 0.35 },
    dailyMin: 38000,
    dailyMax: 78000,
    minDays: 5,
    maxDays: 10,
    flightHours: "約10時間",
    airport: "クイーンズタウン (ZQN)",
    groundNote: "オークランド経由が多い。乗継に半日",
    plan: [
      { day: 1, title: "湖岸", beats: [{ time: "午後", place: "ワカティプ湖", detail: "ボートは任意。岸でいい。" }] },
      { day: 2, title: "グレノーキー", beats: [{ time: "終日", place: "グレノーキー", detail: "日帰り。天候次第。" }] },
    ],
  }),
  intl({
    id: "sydney",
    name: "シドニー",
    country: "オーストラリア",
    city: "シドニー",
    hook: "オペラハウスより、港の朝の光。",
    why: "海の都市で、英語圏の安心感も欲しい人。",
    weights: { solitude: 0.5, novelty: 0.75, slow: 0.58, nature: 0.72, comfort: 0.75, food: 0.68, rest: 0.52, culture: 0.62 },
    dailyMin: 34000,
    dailyMax: 68000,
    minDays: 4,
    maxDays: 8,
    flightHours: "約9時間30分",
    airport: "シドニー (SYD)",
    groundNote: "TrainLink または Uber",
    plan: [
      { day: 1, title: "サーキュラーキー", beats: [{ time: "午後", place: "岩石区", detail: "港沿いを短く。" }] },
      { day: 2, title: "ボンダイ", beats: [{ time: "午前", place: "ボンダイビーチ", detail: "泳がなくていい。" }] },
    ],
  }),
  intl({
    id: "barcelona",
    name: "バルセロナ",
    country: "スペイン",
    city: "バルセロナ",
    hook: "ガウディより、路地の夕方。",
    why: "食と建築と、少し南欧のだらしなさが欲しい人。",
    weights: { solitude: 0.42, novelty: 0.78, slow: 0.55, nature: 0.35, comfort: 0.65, food: 0.88, rest: 0.45, culture: 0.85 },
    dailyMin: 30000,
    dailyMax: 60000,
    minDays: 4,
    maxDays: 7,
    flightHours: "約14時間",
    airport: "BCN",
    groundNote: "Aerobús または メトロ",
    plan: [
      { day: 1, title: "ボケリア", beats: [{ time: "午前", place: "ラ・ボケリア", detail: "朝。混む前。" }] },
      { day: 2, title: "サグラダは外から", beats: [{ time: "午前", place: "サグラダ・ファミリア", detail: "中に入るなら予約。外でも十分。" }] },
    ],
  }),
  intl({
    id: "phuket",
    name: "プーケット",
    country: "タイ",
    city: "プーケット",
    hook: "ビーチリゾートだけど、予定なしでも成立する。",
    why: "休息が最優先で、海外の海が欲しい人。",
    weights: { solitude: 0.55, novelty: 0.65, slow: 0.9, nature: 0.82, comfort: 0.8, food: 0.7, rest: 0.92, culture: 0.3 },
    dailyMin: 20000,
    dailyMax: 42000,
    minDays: 4,
    maxDays: 8,
    flightHours: "約6時間30分",
    airport: "プーケット (HKT)",
    groundNote: "空港からリゾートへ。移動は最小に",
    plan: [
      { day: 1, title: "着いて海", beats: [{ time: "午後", place: "カタビーチ", detail: "一つのビーチだけ。" }] },
      { day: 2, title: "何もしない", beats: [{ time: "終日", place: "宿", detail: "プールか海。どちらか。" }] },
    ],
  }),
  intl({
    id: "busan",
    name: "釜山",
    country: "韓国",
    city: "釜山",
    hook: "海と市場。ソウルより海が近い。",
    why: "近場の海外。食べ歩き向き。",
    weights: { solitude: 0.42, novelty: 0.7, slow: 0.45, nature: 0.35, comfort: 0.65, food: 0.9, rest: 0.4, culture: 0.55 },
    dailyMin: 20000,
    dailyMax: 38000,
    minDays: 2,
    maxDays: 4,
    flightHours: "約2時間",
    airport: "金海 (PUS)",
    groundNote: "空港鉄道または タクシー",
    plan: [
      { day: 1, title: "海雲台", beats: [{ time: "午後", place: "海雲台", detail: "海を見るだけ。" }] },
    ],
  }),
  intl({
    id: "jeju",
    name: "済州島",
    country: "韓国",
    city: "済州島",
    hook: "火山島と、柑橘の香り。",
    why: "国内旅行の延長より、島の空気。",
    weights: { solitude: 0.58, novelty: 0.72, slow: 0.78, nature: 0.85, comfort: 0.68, food: 0.65, rest: 0.75, culture: 0.45 },
    dailyMin: 22000,
    dailyMax: 42000,
    minDays: 3,
    maxDays: 6,
    flightHours: "約2時間30分",
    airport: "済州 (CJU)",
    groundNote: "レンタカー推奨。移動は1日1回",
    plan: [{ day: 1, title: "城山", beats: [{ time: "朝", place: "城山日出峰", detail: "早朝だけ。" }] }],
  }),
  intl({
    id: "tainan",
    name: "台南",
    country: "台湾",
    city: "台南",
    hook: "台湾の古い都。食の深さ。",
    why: "台北より、歴史と食。",
    weights: { solitude: 0.48, novelty: 0.68, slow: 0.62, nature: 0.25, comfort: 0.6, food: 0.95, rest: 0.45, culture: 0.75 },
    dailyMin: 18000,
    dailyMax: 35000,
    minDays: 2,
    maxDays: 5,
    flightHours: "約3時間30分",
    airport: "台南 (TNN) or 高雄経由",
    groundNote: "市内は徒歩とバス",
    plan: [{ day: 1, title: "赤嵌楼", beats: [{ time: "午後", place: "赤嵌楼", detail: "夕方の光。" }] }],
  }),
  intl({
    id: "chiangmai",
    name: "チェンマイ",
    country: "タイ",
    city: "チェンマイ",
    hook: "寺院と、ナイトバザール。",
    why: "バンコクより、ゆっくり。",
    weights: { solitude: 0.55, novelty: 0.78, slow: 0.72, nature: 0.45, comfort: 0.62, food: 0.88, rest: 0.65, culture: 0.8 },
    dailyMin: 16000,
    dailyMax: 32000,
    minDays: 3,
    maxDays: 7,
    flightHours: "約6時間",
    airport: "CNX",
    groundNote: "Grab または 赤トラ",
    plan: [{ day: 1, title: "旧市街", beats: [{ time: "午前", place: "ワット・プラシン", detail: "寺は一つ。" }] }],
  }),
  intl({
    id: "kualalumpur",
    name: "クアラルンプール",
    country: "マレーシア",
    city: "クアラルンプール",
    hook: "双子の塔と、 hawker。",
    why: "多文化と、食。",
    weights: { solitude: 0.4, novelty: 0.75, slow: 0.42, nature: 0.28, comfort: 0.72, food: 0.92, rest: 0.4, culture: 0.65 },
    dailyMin: 18000,
    dailyMax: 35000,
    minDays: 3,
    maxDays: 5,
    flightHours: "約7時間",
    airport: "KUL",
    groundNote: "KLIA Express",
    plan: [{ day: 1, title: "中央市場", beats: [{ time: "夜", place: "ホーカー", detail: "一皿決める。" }] }],
  }),
  intl({
    id: "danang",
    name: "ダナン",
    country: "ベトナム",
    city: "ダナン",
    hook: "美渓と、海。",
    why: "ホーチミンより、リゾート寄り。",
    weights: { solitude: 0.5, novelty: 0.72, slow: 0.75, nature: 0.78, comfort: 0.68, food: 0.75, rest: 0.8, culture: 0.45 },
    dailyMin: 17000,
    dailyMax: 34000,
    minDays: 3,
    maxDays: 6,
    flightHours: "約5時間30分",
    airport: "DAD",
    groundNote: "Grab。ホイアンへ日帰り可",
    plan: [{ day: 1, title: "美渓", beats: [{ time: "午前", place: "美渓", detail: "早朝。" }] }],
  }),
  intl({
    id: "london",
    name: "ロンドン",
    country: "イギリス",
    city: "ロンドン",
    hook: "雨と、博物館。",
    why: "定番の海外都市。",
    weights: { solitude: 0.45, novelty: 0.82, slow: 0.52, nature: 0.25, comfort: 0.7, food: 0.65, rest: 0.45, culture: 0.92 },
    dailyMin: 38000,
    dailyMax: 78000,
    minDays: 4,
    maxDays: 8,
    flightHours: "約12時間30分",
    airport: "LHR",
    groundNote: "Heathrow Express",
    plan: [{ day: 1, title: "テムズ", beats: [{ time: "午後", place: "サウスバンク", detail: "歩くだけ。" }] }],
  }),
  intl({
    id: "amsterdam",
    name: "アムステルダム",
    country: "オランダ",
    city: "アムステルダム",
    hook: "運河と、自転車。",
    why: "歩幅が遅くなる街。",
    weights: { solitude: 0.5, novelty: 0.78, slow: 0.72, nature: 0.35, comfort: 0.65, food: 0.62, rest: 0.55, culture: 0.82 },
    dailyMin: 35000,
    dailyMax: 70000,
    minDays: 4,
    maxDays: 7,
    flightHours: "約12時間",
    airport: "AMS",
    groundNote: "鉄道で市内",
    plan: [{ day: 1, title: "運河", beats: [{ time: "午後", place: "運河沿い", detail: "一方向だけ。" }] }],
  }),
  intl({
    id: "prague",
    name: "プラハ",
    country: "チェコ",
    city: "プラハ",
    hook: "赤い屋根と、橋。",
    why: "中欧の美術館のような街。",
    weights: { solitude: 0.52, novelty: 0.8, slow: 0.68, nature: 0.3, comfort: 0.62, food: 0.68, rest: 0.52, culture: 0.88 },
    dailyMin: 28000,
    dailyMax: 55000,
    minDays: 3,
    maxDays: 6,
    flightHours: "約12時間",
    airport: "PRG",
    groundNote: "AE バス",
    plan: [{ day: 1, title: "旧市街", beats: [{ time: "夕方", place: "查理橋", detail: "人が減る時間。" }] }],
  }),
  intl({
    id: "santorini",
    name: "サントリーニ",
    country: "ギリシャ",
    city: "サントリーニ",
    hook: "白と青の島。",
    why: "休息と、景色。",
    weights: { solitude: 0.58, novelty: 0.85, slow: 0.88, nature: 0.72, comfort: 0.75, food: 0.7, rest: 0.85, culture: 0.6 },
    dailyMin: 32000,
    dailyMax: 65000,
    minDays: 4,
    maxDays: 7,
    flightHours: "約14時間",
    airport: "JTR",
    groundNote: "アテネ経由が多い",
    plan: [{ day: 1, title: "イア", beats: [{ time: "夕方", place: "イア", detail: "日没。" }] }],
  }),
  intl({
    id: "dubai",
    name: "ドバイ",
    country: "UAE",
    city: "ドバイ",
    hook: "砂漠と、超高層。",
    why: "非日常のスケール。",
    weights: { solitude: 0.4, novelty: 0.9, slow: 0.45, nature: 0.35, comfort: 0.9, food: 0.65, rest: 0.55, culture: 0.5 },
    dailyMin: 35000,
    dailyMax: 80000,
    minDays: 3,
    maxDays: 6,
    flightHours: "約10時間",
    airport: "DXB",
    groundNote: "メトロ",
    plan: [{ day: 1, title: "旧市街", beats: [{ time: "午後", place: "デイラ", detail: "スークを短く。" }] }],
  }),
  intl({
    id: "melbourne",
    name: "メルボルン",
    country: "オーストラリア",
    city: "メルボルン",
    hook: "カフェと、路地。",
    why: "シドニーと違う、南の文化。",
    weights: { solitude: 0.48, novelty: 0.75, slow: 0.62, nature: 0.4, comfort: 0.75, food: 0.85, rest: 0.5, culture: 0.72 },
    dailyMin: 34000,
    dailyMax: 68000,
    minDays: 4,
    maxDays: 8,
    flightHours: "約10時間",
    airport: "MEL",
    groundNote: "SkyBus",
    plan: [{ day: 1, title: "フリンダース", beats: [{ time: "午後", place: "ホジアレーン", detail: "路地。" }] }],
  }),
  intl({
    id: "cairns",
    name: "ケアンズ",
    country: "オーストラリア",
    city: "ケアンズ",
    hook: "グレートバリアリーフ。",
    why: "海のスケール。",
    weights: { solitude: 0.55, novelty: 0.82, slow: 0.7, nature: 0.92, comfort: 0.7, food: 0.55, rest: 0.72, culture: 0.35 },
    dailyMin: 36000,
    dailyMax: 72000,
    minDays: 4,
    maxDays: 8,
    flightHours: "約9時間30分",
    airport: "CNS",
    groundNote: "バス",
    plan: [{ day: 1, title: "海", beats: [{ time: "終日", place: "リーフ", detail: "ボートは一便。" }] }],
  }),
  intl({
    id: "la",
    name: "ロサンゼルス",
    country: "アメリカ",
    city: "ロサンゼルス",
    hook: "海と、スプrawl。",
    why: "カリフォルニアの光。",
    weights: { solitude: 0.45, novelty: 0.8, slow: 0.48, nature: 0.55, comfort: 0.72, food: 0.78, rest: 0.5, culture: 0.7 },
    dailyMin: 38000,
    dailyMax: 82000,
    minDays: 4,
    maxDays: 8,
    flightHours: "約11時間",
    airport: "LAX",
    groundNote: "Uber。レンタカー任意",
    plan: [{ day: 1, title: "サンタモニカ", beats: [{ time: "夕方", place: "サンタモニカ", detail: "海。" }] }],
  }),
  intl({
    id: "sf",
    name: "サンフランシスコ",
    country: "アメリカ",
    city: "サンフランシスコ",
    hook: "坂と、湾。",
    why: "LAより、歩ける。",
    weights: { solitude: 0.48, novelty: 0.78, slow: 0.55, nature: 0.5, comfort: 0.68, food: 0.82, rest: 0.48, culture: 0.75 },
    dailyMin: 40000,
    dailyMax: 85000,
    minDays: 4,
    maxDays: 7,
    flightHours: "約9時間30分",
    airport: "SFO",
    groundNote: "BART",
    plan: [{ day: 1, title: "ピア39", beats: [{ time: "午後", place: "フィッシャーマンズワーフ", detail: "短く。" }] }],
  }),
  intl({
    id: "zurich",
    name: "チューリッヒ",
    country: "スイス",
    city: "チューリッヒ",
    hook: "湖と、旧市街。",
    why: "アルプスへの入口。",
    weights: { solitude: 0.55, novelty: 0.78, slow: 0.72, nature: 0.78, comfort: 0.82, food: 0.65, rest: 0.62, culture: 0.7 },
    dailyMin: 45000,
    dailyMax: 90000,
    minDays: 3,
    maxDays: 7,
    flightHours: "約12時間",
    airport: "ZRH",
    groundNote: "鉄道",
    plan: [{ day: 1, title: "湖", beats: [{ time: "午後", place: "チューリッヒ湖", detail: "ボートは任意。" }] }],
  }),
  intl({
    id: "marrakech",
    name: "マラケシュ",
    country: "モロッコ",
    city: "マラケシュ",
    hook: "スークと、プラザ。",
    why: "色と、音。",
    weights: { solitude: 0.38, novelty: 0.92, slow: 0.48, nature: 0.35, comfort: 0.48, food: 0.75, rest: 0.4, culture: 0.85 },
    dailyMin: 25000,
    dailyMax: 50000,
    minDays: 4,
    maxDays: 7,
    flightHours: "約15時間",
    airport: "RAK",
    groundNote: "メディナは徒歩",
    plan: [{ day: 1, title: "メディナ", beats: [{ time: "夕方", place: "ジェマ・エル・フナ", detail: "音と匂い。" }] }],
  }),
  intl({
    id: "vienna",
    name: "ウィーン",
    country: "オーストリア",
    city: "ウィーン",
    hook: "カフェと、宮殿。",
    why: "中欧の落ち着き。",
    weights: { solitude: 0.52, novelty: 0.75, slow: 0.75, nature: 0.28, comfort: 0.78, food: 0.72, rest: 0.58, culture: 0.9 },
    dailyMin: 33000,
    dailyMax: 68000,
    minDays: 4,
    maxDays: 7,
    flightHours: "約12時間",
    airport: "VIE",
    groundNote: "CAT",
    plan: [{ day: 1, title: "カフェ", beats: [{ time: "午前", place: "カフェ", detail: "一軒、長く。" }] }],
  }),
  intl({
    id: "siemreap",
    name: "シェムリアップ",
    country: "カンボジア",
    city: "シェムリアップ",
    hook: "アンコールワットの朝。",
    why: "一生に一度、級の遺跡。",
    weights: { solitude: 0.5, novelty: 0.9, slow: 0.55, nature: 0.45, comfort: 0.52, food: 0.65, rest: 0.45, culture: 0.95 },
    dailyMin: 18000,
    dailyMax: 38000,
    minDays: 4,
    maxDays: 7,
    flightHours: "約6時間30分",
    airport: "REP",
    groundNote: "tuk-tuk",
    plan: [{ day: 1, title: "小回り", beats: [{ time: "早朝", place: "アンコールワット", detail: "日の出。" }] }],
  }),
  intl({
    id: "penang",
    name: "ペナン",
    country: "マレーシア",
    city: "ペナン",
    hook: "ストリートアートと、 hawker。",
    why: "KLより、のんびり。",
    weights: { solitude: 0.52, novelty: 0.72, slow: 0.68, nature: 0.38, comfort: 0.62, food: 0.9, rest: 0.55, culture: 0.68 },
    dailyMin: 17000,
    dailyMax: 34000,
    minDays: 3,
    maxDays: 6,
    flightHours: "約7時間",
    airport: "PEN",
    groundNote: "Grab",
    plan: [{ day: 1, title: "ジョージタウン", beats: [{ time: "午後", place: "壁画", detail: "歩く。" }] }],
  }),
  intl({
    id: "hochiminh",
    name: "ホーチミン",
    country: "ベトナム",
    city: "ホーチミン",
    hook: "バイクと、コーヒー。",
    why: "ハノイより、活気。",
    weights: { solitude: 0.38, novelty: 0.85, slow: 0.42, nature: 0.22, comfort: 0.48, food: 0.92, rest: 0.35, culture: 0.65 },
    dailyMin: 15000,
    dailyMax: 30000,
    minDays: 3,
    maxDays: 6,
    flightHours: "約6時間",
    airport: "SGN",
    groundNote: "Grab",
    plan: [{ day: 1, title: "1区", beats: [{ time: "夜", place: "ベンタイン", detail: "短く。" }] }],
  }),
  intl({
    id: "berlin",
    name: "ベルリン",
    country: "ドイツ",
    city: "ベルリン",
    hook: "歴史と、クラブ。",
    why: "欧州の今。",
    weights: { solitude: 0.45, novelty: 0.85, slow: 0.5, nature: 0.25, comfort: 0.62, food: 0.68, rest: 0.42, culture: 0.88 },
    dailyMin: 30000,
    dailyMax: 62000,
    minDays: 4,
    maxDays: 7,
    flightHours: "約12時間",
    airport: "BER",
    groundNote: "U-Bahn",
    plan: [{ day: 1, title: "東側", beats: [{ time: "午後", place: "ミッテ", detail: "歩く。" }] }],
  }),
  intl({
    id: "seattle",
    name: "シアトル",
    country: "アメリカ",
    city: "シアトル",
    hook: "雨と、コーヒー。",
    why: "西海岸の落ち着き。",
    weights: { solitude: 0.52, novelty: 0.72, slow: 0.58, nature: 0.62, comfort: 0.7, food: 0.75, rest: 0.52, culture: 0.68 },
    dailyMin: 36000,
    dailyMax: 75000,
    minDays: 4,
    maxDays: 7,
    flightHours: "約9時間",
    airport: "SEA",
    groundNote: "Link Light Rail",
    plan: [{ day: 1, title: "パイク", beats: [{ time: "午前", place: "パイクプレイス", detail: "朝。" }] }],
  }),
  intl({
    id: "munich",
    name: "ミュンヘン",
    country: "ドイツ",
    city: "ミュンヘン",
    hook: "ビールと、旧市街。",
    why: "ベルリンより、南ドイツ。",
    weights: { solitude: 0.48, novelty: 0.78, slow: 0.62, nature: 0.35, comfort: 0.72, food: 0.82, rest: 0.52, culture: 0.85 },
    dailyMin: 32000, dailyMax: 65000, minDays: 3, maxDays: 6,
    flightHours: "約12時間", airport: "MUC", groundNote: "S-Bahn",
    plan: [{ day: 1, title: "マリエン", beats: [{ time: "午後", place: "マリエン広場", detail: "歩く。" }] }],
  }),
  intl({
    id: "florence",
    name: "フィレンツェ",
    country: "イタリア",
    city: "フィレンツェ",
    hook: "ルネサンスの街。",
    why: "ローマより、美術。",
    weights: { solitude: 0.45, novelty: 0.82, slow: 0.58, nature: 0.22, comfort: 0.68, food: 0.88, rest: 0.45, culture: 0.95 },
    dailyMin: 34000, dailyMax: 70000, minDays: 3, maxDays: 6,
    flightHours: "約13時間", airport: "FLR", groundNote: "トラム",
    plan: [{ day: 1, title: "ウフィツィ", beats: [{ time: "午前", place: "ウフィツィ", detail: "予約。" }] }],
  }),
  intl({
    id: "venice",
    name: "ヴェネツィア",
    country: "イタリア",
    city: "ヴェネツィア",
    hook: "水の都。",
    why: "歩幅が遅くなる。",
    weights: { solitude: 0.42, novelty: 0.9, slow: 0.72, nature: 0.28, comfort: 0.62, food: 0.75, rest: 0.55, culture: 0.92 },
    dailyMin: 36000, dailyMax: 75000, minDays: 2, maxDays: 5,
    flightHours: "約13時間", airport: "VCE", groundNote: "ヴァポレット",
    plan: [{ day: 1, title: "サンマルコ", beats: [{ time: "早朝", place: "サンマルコ", detail: "人が少ない。" }] }],
  }),
  intl({
    id: "istanbul",
    name: "イスタンブール",
    country: "トルコ",
    city: "イスタンブール",
    hook: "アジアと欧州の間。",
    why: "東西の交差点。",
    weights: { solitude: 0.4, novelty: 0.92, slow: 0.48, nature: 0.25, comfort: 0.55, food: 0.9, rest: 0.42, culture: 0.9 },
    dailyMin: 22000, dailyMax: 45000, minDays: 4, maxDays: 7,
    flightHours: "約12時間", airport: "IST", groundNote: "トラム",
    plan: [{ day: 1, title: "グランドバザール", beats: [{ time: "午前", place: "バザール", detail: "短く。" }] }],
  }),
  intl({
    id: "budapest",
    name: "ブダペスト",
    country: "ハンガリー",
    city: "ブダペスト",
    hook: "温泉と、ドナウ。",
    why: "中欧の美しさ。",
    weights: { solitude: 0.48, novelty: 0.8, slow: 0.65, nature: 0.28, comfort: 0.62, food: 0.72, rest: 0.62, culture: 0.85 },
    dailyMin: 26000, dailyMax: 52000, minDays: 3, maxDays: 6,
    flightHours: "約13時間", airport: "BUD", groundNote: "地下鉄",
    plan: [{ day: 1, title: "セーチェーニ", beats: [{ time: "午後", place: "温泉", detail: "一軒。" }] }],
  }),
  intl({
    id: "cairo",
    name: "カイロ",
    country: "エジプト",
    city: "カイロ",
    hook: "ピラミッドと、ナイル。",
    why: "古代のスケール。",
    weights: { solitude: 0.38, novelty: 0.95, slow: 0.45, nature: 0.22, comfort: 0.45, food: 0.65, rest: 0.38, culture: 0.95 },
    dailyMin: 20000, dailyMax: 42000, minDays: 4, maxDays: 7,
    flightHours: "約13時間", airport: "CAI", groundNote: "Uber",
    plan: [{ day: 1, title: "ギザ", beats: [{ time: "朝", place: "ピラミッド", detail: "早朝。" }] }],
  }),
  intl({
    id: "capetown",
    name: "ケープタウン",
    country: "南アフリカ",
    city: "ケープタウン",
    hook: "テーブルマウンテン。",
    why: "海と山。",
    weights: { solitude: 0.5, novelty: 0.88, slow: 0.55, nature: 0.88, comfort: 0.62, food: 0.68, rest: 0.52, culture: 0.72 },
    dailyMin: 28000, dailyMax: 58000, minDays: 5, maxDays: 10,
    flightHours: "約17時間", airport: "CPT", groundNote: "Uber",
    plan: [{ day: 1, title: "テーブル", beats: [{ time: "午前", place: "ロープウェイ", detail: "天気次第。" }] }],
  }),
  intl({
    id: "toronto",
    name: "トロント",
    country: "カナダ",
    city: "トロント",
    hook: "CNタワーと、多文化。",
    why: "バンクーバーと違う東。",
    weights: { solitude: 0.45, novelty: 0.75, slow: 0.52, nature: 0.35, comfort: 0.78, food: 0.78, rest: 0.48, culture: 0.72 },
    dailyMin: 34000, dailyMax: 68000, minDays: 4, maxDays: 8,
    flightHours: "約12時間", airport: "YYZ", groundNote: "UP Express",
    plan: [{ day: 1, title: "ストローベリー", beats: [{ time: "午後", place: "St. Lawrence", detail: "市場。" }] }],
  }),
  intl({
    id: "boston",
    name: "ボストン",
    country: "アメリカ",
    city: "ボストン",
    hook: "歴史と、大学。",
    why: "NYより、歩ける。",
    weights: { solitude: 0.48, novelty: 0.72, slow: 0.55, nature: 0.32, comfort: 0.72, food: 0.78, rest: 0.48, culture: 0.82 },
    dailyMin: 36000, dailyMax: 72000, minDays: 3, maxDays: 6,
    flightHours: "約13時間", airport: "BOS", groundNote: "Silver Line",
    plan: [{ day: 1, title: "フリーダム", beats: [{ time: "午前", place: "トレイル", detail: "短く。" }] }],
  }),
  intl({
    id: "chicago",
    name: "シカゴ",
    country: "アメリカ",
    city: "シカゴ",
    hook: "ミレニアムパーク。",
    why: "中西部の都市。",
    weights: { solitude: 0.42, novelty: 0.78, slow: 0.48, nature: 0.28, comfort: 0.72, food: 0.85, rest: 0.42, culture: 0.78 },
    dailyMin: 36000, dailyMax: 75000, minDays: 3, maxDays: 6,
    flightHours: "約12時間", airport: "ORD", groundNote: "CTA",
    plan: [{ day: 1, title: "ミシガン", beats: [{ time: "午後", place: "湖畔", detail: "歩く。" }] }],
  }),
  intl({
    id: "tahiti",
    name: "タヒチ",
    country: "フランス領ポリネシア",
    city: "パペーテ",
    hook: "南の青。",
    why: "ハワイより、遠い。",
    weights: { solitude: 0.55, novelty: 0.92, slow: 0.88, nature: 0.92, comfort: 0.75, food: 0.65, rest: 0.9, culture: 0.55 },
    dailyMin: 45000, dailyMax: 95000, minDays: 5, maxDays: 10,
    flightHours: "約11時間", airport: "PPT", groundNote: "タクシー",
    plan: [{ day: 1, title: "海", beats: [{ time: "終日", place: "ビーチ", detail: "何もしない。" }] }],
  }),
  intl({
    id: "maldives",
    name: "モルディブ",
    country: "モルディブ",
    city: "マレ",
    hook: "水上ヴィラ。",
    why: "休息の極致。",
    weights: { solitude: 0.62, novelty: 0.88, slow: 0.92, nature: 0.95, comfort: 0.88, food: 0.6, rest: 0.95, culture: 0.35 },
    dailyMin: 55000, dailyMax: 120000, minDays: 4, maxDays: 8,
    flightHours: "約9時間", airport: "MLE", groundNote: "水上飛行機",
    plan: [{ day: 1, title: "到着", beats: [{ time: "午後", place: "リゾート", detail: "移動だけ。" }] }],
  }),
  intl({
    id: "luangprabang",
    name: "ルアンパバーン",
    country: "ラオス",
    city: "ルアンパバーン",
    hook: "早朝の托鉢。",
    why: "タイより、静か。",
    weights: { solitude: 0.58, novelty: 0.85, slow: 0.85, nature: 0.45, comfort: 0.48, food: 0.72, rest: 0.72, culture: 0.88 },
    dailyMin: 14000, dailyMax: 28000, minDays: 3, maxDays: 6,
    flightHours: "約6時間30分", airport: "LPQ", groundNote: "徒歩",
    plan: [{ day: 1, title: "早朝", beats: [{ time: "早朝", place: "通り", detail: "托鉢。" }] }],
  }),
  intl({
    id: "cebu",
    name: "セブ",
    country: "フィリピン",
    city: "セブ",
    hook: "島と、教会。",
    why: "マニラより、海。",
    weights: { solitude: 0.48, novelty: 0.78, slow: 0.65, nature: 0.72, comfort: 0.55, food: 0.75, rest: 0.68, culture: 0.62 },
    dailyMin: 15000, dailyMax: 32000, minDays: 3, maxDays: 7,
    flightHours: "約4時間30分", airport: "CEB", groundNote: "Grab",
    plan: [{ day: 1, title: "マクタン", beats: [{ time: "午後", place: "ビーチ", detail: "一つ。" }] }],
  }),
  intl({
    id: "delhi",
    name: "デリー",
    country: "インド",
    city: "ニューデリー",
    hook: "色と、スパイス。",
    why: "圧倒的な密度。",
    weights: { solitude: 0.32, novelty: 0.95, slow: 0.38, nature: 0.18, comfort: 0.42, food: 0.92, rest: 0.32, culture: 0.88 },
    dailyMin: 16000, dailyMax: 35000, minDays: 4, maxDays: 8,
    flightHours: "約8時間30分", airport: "DEL", groundNote: "メトロ",
    plan: [{ day: 1, title: "旧市街", beats: [{ time: "午前", place: "レッドフォート", detail: "短く。" }] }],
  }),
  intl({
    id: "kathmandu",
    name: "カトマンズ",
    country: "ネパール",
    city: "カトマンズ",
    hook: "ヒマラヤの入口。",
    why: "山のスケール。",
    weights: { solitude: 0.52, novelty: 0.9, slow: 0.55, nature: 0.88, comfort: 0.42, food: 0.65, rest: 0.48, culture: 0.85 },
    dailyMin: 12000, dailyMax: 28000, minDays: 5, maxDays: 12,
    flightHours: "約6時間30分", airport: "KTM", groundNote: "タクシー",
    plan: [{ day: 1, title: "ダルバール", beats: [{ time: "午前", place: "広場", detail: "歩く。" }] }],
  }),
  intl({
    id: "stockholm",
    name: "ストックホルム",
    country: "スウェーデン",
    city: "ストックホルム",
    hook: "北欧の水都。",
    why: "レイキャビクより、都市。",
    weights: { solitude: 0.52, novelty: 0.78, slow: 0.68, nature: 0.42, comfort: 0.78, food: 0.68, rest: 0.58, culture: 0.82 },
    dailyMin: 38000, dailyMax: 78000, minDays: 4, maxDays: 7,
    flightHours: "約11時間", airport: "ARN", groundNote: "Arlanda Express",
    plan: [{ day: 1, title: "ガムラ", beats: [{ time: "午後", place: "旧市街", detail: "歩く。" }] }],
  }),
  intl({
    id: "helsinki",
    name: "ヘルシンキ",
    country: "フィンランド",
    city: "ヘルシンキ",
    hook: "サウナと、デザイン。",
    why: "北欧の入口。",
    weights: { solitude: 0.55, novelty: 0.75, slow: 0.72, nature: 0.38, comfort: 0.78, food: 0.65, rest: 0.68, culture: 0.78 },
    dailyMin: 36000, dailyMax: 72000, minDays: 3, maxDays: 6,
    flightHours: "約10時間30分", airport: "HEL", groundNote: "トラム",
    plan: [{ day: 1, title: "サウナ", beats: [{ time: "午後", place: "サウナ", detail: "一軒。" }] }],
  }),
  intl({
    id: "milan",
    name: "ミラノ",
    country: "イタリア",
    city: "ミラノ",
    hook: "ドゥオモと、ファッション。",
    why: "フィレンツェより、都市。",
    weights: { solitude: 0.42, novelty: 0.8, slow: 0.48, nature: 0.2, comfort: 0.75, food: 0.85, rest: 0.42, culture: 0.85 },
    dailyMin: 35000, dailyMax: 72000, minDays: 2, maxDays: 5,
    flightHours: "約13時間", airport: "MXP", groundNote: "Malpensa Express",
    plan: [{ day: 1, title: "ドゥオモ", beats: [{ time: "午前", place: "大聖堂", detail: "外から。" }] }],
  }),
  intl({
    id: "mexicocity",
    name: "メキシコシティ",
    country: "メキシコ",
    city: "メキシコシティ",
    hook: "テオティワカンと、タコス。",
    why: "中南米の巨大都市。",
    weights: { solitude: 0.38, novelty: 0.9, slow: 0.42, nature: 0.25, comfort: 0.52, food: 0.95, rest: 0.38, culture: 0.88 },
    dailyMin: 22000, dailyMax: 48000, minDays: 4, maxDays: 8,
    flightHours: "約14時間", airport: "MEX", groundNote: "Uber",
    plan: [{ day: 1, title: "Centro", beats: [{ time: "午前", place: "中心部", detail: "短く。" }] }],
  }),
  intl({
    id: "colombo",
    name: "コロンボ",
    country: "スリランカ",
    city: "コロンボ",
    hook: "紅茶と、仏教。",
    why: "南アジアの島。",
    weights: { solitude: 0.5, novelty: 0.82, slow: 0.62, nature: 0.55, comfort: 0.48, food: 0.78, rest: 0.55, culture: 0.82 },
    dailyMin: 14000, dailyMax: 30000, minDays: 5, maxDays: 10,
    flightHours: "約8時間", airport: "CMB", groundNote: "タクシー",
    plan: [{ day: 1, title: "ガル", beats: [{ time: "午後", place: "旧市街", detail: "日帰り可。" }] }],
  }),
  intl({
    id: "mumbai",
    name: "ムンバイ",
    country: "インド",
    city: "ムンバイ",
    hook: "ボリウッドと、海。",
    why: "デリーと違う、海の都市。",
    weights: { solitude: 0.35, novelty: 0.92, slow: 0.4, nature: 0.28, comfort: 0.48, food: 0.9, rest: 0.35, culture: 0.82 },
    dailyMin: 17000, dailyMax: 38000, minDays: 4, maxDays: 8,
    flightHours: "約8時間30分", airport: "BOM", groundNote: "Uber",
    plan: [{ day: 1, title: "ゲートウェイ", beats: [{ time: "夕方", place: "インド門", detail: "海。" }] }],
  }),
  intl({
    id: "porto",
    name: "ポルト",
    country: "ポルトガル",
    city: "ポルト",
    hook: "ポートワインと、坂。",
    why: "リスボンより、静か。",
    weights: { solitude: 0.52, novelty: 0.78, slow: 0.68, nature: 0.32, comfort: 0.65, food: 0.82, rest: 0.55, culture: 0.82 },
    dailyMin: 28000, dailyMax: 55000, minDays: 3, maxDays: 6,
    flightHours: "約14時間", airport: "OPO", groundNote: "メトロ",
    plan: [{ day: 1, title: "リベイラ", beats: [{ time: "夕方", place: "川沿い", detail: "歩く。" }] }],
  }),
  intl({
    id: "copenhagen",
    name: "コペンハーゲン",
    country: "デンマーク",
    city: "コペンハーゲン",
    hook: "北欧の幸福。",
    why: "自転車の街。",
    weights: { solitude: 0.5, novelty: 0.75, slow: 0.72, nature: 0.35, comfort: 0.82, food: 0.72, rest: 0.62, culture: 0.78 },
    dailyMin: 40000, dailyMax: 82000, minDays: 3, maxDays: 6,
    flightHours: "約11時間30分", airport: "CPH", groundNote: "メトロ",
    plan: [{ day: 1, title: "ニホン", beats: [{ time: "午後", place: "Nyhavn", detail: "歩く。" }] }],
  }),
  intl({
    id: "kaohsiung",
    name: "高雄",
    country: "台湾",
    city: "高雄",
    hook: "港と、夜市。",
    why: "台北より、南。",
    weights: { solitude: 0.42, novelty: 0.72, slow: 0.48, nature: 0.28, comfort: 0.62, food: 0.92, rest: 0.42, culture: 0.65 },
    dailyMin: 18000, dailyMax: 35000, minDays: 3, maxDays: 6,
    flightHours: "約3時間30分", airport: "KHH", groundNote: "MRT",
    plan: [{ day: 1, title: "蓮池潭", beats: [{ time: "夕方", place: "龍虎塔", detail: "短く。" }] }],
  }),
  intl({
    id: "macau",
    name: "マカオ",
    country: "中国",
    city: "マカオ",
    hook: "ポルトガルと、中華。",
    why: "香港から、日帰り。",
    weights: { solitude: 0.38, novelty: 0.82, slow: 0.45, nature: 0.15, comfort: 0.75, food: 0.88, rest: 0.4, culture: 0.78 },
    dailyMin: 22000, dailyMax: 45000, minDays: 2, maxDays: 4,
    flightHours: "約4時間30分", airport: "MFM", groundNote: "バス",
    plan: [{ day: 1, title: "旧市街", beats: [{ time: "午後", place: "セナド", detail: "歩く。" }] }],
  }),
  intl({
    id: "miami",
    name: "マイアミ",
    country: "アメリカ",
    city: "マイアミ",
    hook: "ビーチと、Art Deco。",
    why: "LAより、南国。",
    weights: { solitude: 0.45, novelty: 0.8, slow: 0.52, nature: 0.55, comfort: 0.78, food: 0.75, rest: 0.65, culture: 0.68 },
    dailyMin: 40000, dailyMax: 85000, minDays: 4, maxDays: 8,
    flightHours: "約14時間", airport: "MIA", groundNote: "Uber",
    plan: [{ day: 1, title: "サウスビーチ", beats: [{ time: "午後", place: "ビーチ", detail: "一つ。" }] }],
  }),
  intl({
    id: "rio",
    name: "リオデジャネイロ",
    country: "ブラジル",
    city: "リオ",
    hook: "コルコバードと、海。",
    why: "南米の定番。",
    weights: { solitude: 0.4, novelty: 0.9, slow: 0.48, nature: 0.72, comfort: 0.55, food: 0.72, rest: 0.48, culture: 0.82 },
    dailyMin: 28000, dailyMax: 58000, minDays: 5, maxDays: 10,
    flightHours: "約24時間", airport: "GIG", groundNote: "Uber",
    plan: [{ day: 1, title: "イパネマ", beats: [{ time: "夕方", place: "ビーチ", detail: "歩く。" }] }],
  }),
  intl({
    id: "madrid",
    name: "マドリード",
    country: "スペイン",
    city: "マドリード",
    hook: "美術館と、タパス。",
    why: "バルセロナと対。",
    weights: { solitude: 0.42, novelty: 0.82, slow: 0.5, nature: 0.22, comfort: 0.72, food: 0.9, rest: 0.45, culture: 0.88 },
    dailyMin: 32000, dailyMax: 68000, minDays: 4, maxDays: 7,
    flightHours: "約14時間", airport: "MAD", groundNote: "メトロ",
    plan: [{ day: 1, title: "プレイマ", beats: [{ time: "午後", place: "広場", detail: "歩く。" }] }],
  }),
  intl({
    id: "seville",
    name: "セビリア",
    country: "スペイン",
    city: "セビリア",
    hook: "フラメンコと、orange。",
    why: "マドリードより、南。",
    weights: { solitude: 0.45, novelty: 0.85, slow: 0.58, nature: 0.25, comfort: 0.65, food: 0.85, rest: 0.52, culture: 0.9 },
    dailyMin: 30000, dailyMax: 62000, minDays: 3, maxDays: 6,
    flightHours: "約15時間", airport: "SVQ", groundNote: "トラム",
    plan: [{ day: 1, title: "アルカサル", beats: [{ time: "午前", place: "宮殿", detail: "予約。" }] }],
  }),
  intl({
    id: "naples",
    name: "ナポリ",
    country: "イタリア",
    city: "ナポリ",
    hook: "ピザと、ベスビオ。",
    why: "ローマより、生々しい。",
    weights: { solitude: 0.35, novelty: 0.85, slow: 0.42, nature: 0.35, comfort: 0.48, food: 0.95, rest: 0.38, culture: 0.82 },
    dailyMin: 28000, dailyMax: 55000, minDays: 3, maxDays: 6,
    flightHours: "約14時間", airport: "NAP", groundNote: "メトロ",
    plan: [{ day: 1, title: "ポンペイ", beats: [{ time: "終日", place: "遺跡", detail: "一つ。" }] }],
  }),
  intl({
    id: "doha",
    name: "ドーハ",
    country: "カタール",
    city: "ドーハ",
    hook: "砂漠と、未来。",
    why: "ドバイより、コンパクト。",
    weights: { solitude: 0.42, novelty: 0.88, slow: 0.48, nature: 0.32, comfort: 0.88, food: 0.68, rest: 0.55, culture: 0.62 },
    dailyMin: 38000, dailyMax: 82000, minDays: 3, maxDays: 6,
    flightHours: "約11時間", airport: "DOH", groundNote: "メトロ",
    plan: [{ day: 1, title: "スーク", beats: [{ time: "夕方", place: "ワクイフ", detail: "短く。" }] }],
  }),
  intl({
    id: "montreal",
    name: "モントリオール",
    country: "カナダ",
    city: "モントリオール",
    hook: "フランス語と、旧市街。",
    why: "トロントより、欧州。",
    weights: { solitude: 0.48, novelty: 0.78, slow: 0.58, nature: 0.32, comfort: 0.75, food: 0.82, rest: 0.5, culture: 0.82 },
    dailyMin: 34000, dailyMax: 70000, minDays: 4, maxDays: 7,
    flightHours: "約13時間", airport: "YUL", groundNote: "メトロ",
    plan: [{ day: 1, title: "旧市街", beats: [{ time: "午後", place: "ノートルダム", detail: "歩く。" }] }],
  }),
  intl({
    id: "krakow",
    name: "クラクフ",
    country: "ポーランド",
    city: "クラクフ",
    hook: "旧市街と、塩鉱。",
    why: "中欧の美しさ。",
    weights: { solitude: 0.5, novelty: 0.82, slow: 0.65, nature: 0.28, comfort: 0.62, food: 0.72, rest: 0.55, culture: 0.88 },
    dailyMin: 24000, dailyMax: 48000, minDays: 3, maxDays: 6,
    flightHours: "約13時間", airport: "KRK", groundNote: "トラム",
    plan: [{ day: 1, title: "中央広場", beats: [{ time: "午後", place: "Rynek", detail: "歩く。" }] }],
  }),
  intl({
    id: "oslo",
    name: "オスロ",
    country: "ノルウェー",
    city: "オスロ",
    hook: "フィヨルドへの入口。",
    why: "北欧の自然。",
    weights: { solitude: 0.55, novelty: 0.8, slow: 0.68, nature: 0.82, comfort: 0.82, food: 0.65, rest: 0.58, culture: 0.75 },
    dailyMin: 45000, dailyMax: 92000, minDays: 4, maxDays: 8,
    flightHours: "約12時間", airport: "OSL", groundNote: "Flytoget",
    plan: [{ day: 1, title: "オペラ", beats: [{ time: "午後", place: "オペラハウス", detail: "外から。" }] }],
  }),
  intl({
    id: "pattaya",
    name: "パタヤ",
    country: "タイ",
    city: "パタヤ",
    hook: "バンコクから、海。",
    why: "短い日数で、リゾート。",
    weights: { solitude: 0.4, novelty: 0.72, slow: 0.55, nature: 0.45, comfort: 0.62, food: 0.78, rest: 0.72, culture: 0.45 },
    dailyMin: 15000, dailyMax: 32000, minDays: 3, maxDays: 6,
    flightHours: "約6時間", airport: "BKK", groundNote: "バス",
    plan: [{ day: 1, title: "海", beats: [{ time: "午後", place: "ビーチ", detail: "一つ。" }] }],
  }),
  intl({
    id: "buenosaires",
    name: "ブエノスアイレス",
    country: "アルゼンチン",
    city: "ブエノスアイレス",
    hook: "タンゴと、肉。",
    why: "南米のParis。",
    weights: { solitude: 0.42, novelty: 0.92, slow: 0.52, nature: 0.25, comfort: 0.58, food: 0.9, rest: 0.45, culture: 0.88 },
    dailyMin: 26000, dailyMax: 52000, minDays: 5, maxDays: 10,
    flightHours: "約24時間", airport: "EZE", groundNote: "Subte",
    plan: [{ day: 1, title: "サン・テルモ", beats: [{ time: "午後", place: "市場", detail: "歩く。" }] }],
  }),
  intl({
    id: "lima",
    name: "リマ",
    country: "ペルー",
    city: "リマ",
    hook: "cevicheと、旧市街。",
    why: "南米の食都。",
    weights: { solitude: 0.4, novelty: 0.88, slow: 0.48, nature: 0.28, comfort: 0.55, food: 0.95, rest: 0.42, culture: 0.82 },
    dailyMin: 22000, dailyMax: 45000, minDays: 4, maxDays: 8,
    flightHours: "約22時間", airport: "LIM", groundNote: "Uber",
    plan: [{ day: 1, title: "Miraflores", beats: [{ time: "夕方", place: "崖", detail: "海。" }] }],
  }),
  intl({
    id: "guam",
    name: "グアム",
    country: "アメリカ",
    city: "グアム",
    hook: "近場の南国。",
    why: "ハワイより、近い。",
    weights: { solitude: 0.48, novelty: 0.72, slow: 0.75, nature: 0.78, comfort: 0.78, food: 0.65, rest: 0.82, culture: 0.45 },
    dailyMin: 32000, dailyMax: 65000, minDays: 3, maxDays: 7,
    flightHours: "約3時間30分", airport: "GUM", groundNote: "レンタカー",
    plan: [{ day: 1, title: "タモン", beats: [{ time: "午後", place: "ビーチ", detail: "一つ。" }] }],
  }),
  intl({
    id: "saipan",
    name: "サイパン",
    country: "アメリカ",
    city: "サイパン",
    hook: "マリアナの青。",
    why: "グアムより、静か。",
    weights: { solitude: 0.55, novelty: 0.78, slow: 0.78, nature: 0.85, comfort: 0.72, food: 0.6, rest: 0.85, culture: 0.4 },
    dailyMin: 30000, dailyMax: 62000, minDays: 4, maxDays: 8,
    flightHours: "約3時間30分", airport: "SPN", groundNote: "タクシー",
    plan: [{ day: 1, title: "ガン", beats: [{ time: "午後", place: "ビーチ", detail: "歩く。" }] }],
  }),
  intl({
    id: "hue",
    name: "フエ",
    country: "ベトナム",
    city: "フエ",
    hook: "旧都と、川。",
    why: "ハノイとホーチミンの間。",
    weights: { solitude: 0.5, novelty: 0.78, slow: 0.62, nature: 0.35, comfort: 0.52, food: 0.82, rest: 0.55, culture: 0.85 },
    dailyMin: 14000, dailyMax: 28000, minDays: 3, maxDays: 6,
    flightHours: "約5時間30分", airport: "HUI", groundNote: "Grab",
    plan: [{ day: 1, title: "皇城", beats: [{ time: "午前", place: "皇城", detail: "短く。" }] }],
  }),
  intl({
    id: "vientiane",
    name: "ビエンチャン",
    country: "ラオス",
    city: "ビエンチャン",
    hook: "メコンと、仏。",
    why: "ルアンパバーンより、都市。",
    weights: { solitude: 0.52, novelty: 0.8, slow: 0.78, nature: 0.38, comfort: 0.48, food: 0.72, rest: 0.68, culture: 0.82 },
    dailyMin: 13000, dailyMax: 26000, minDays: 3, maxDays: 6,
    flightHours: "約6時間", airport: "VTE", groundNote: "tuk-tuk",
    plan: [{ day: 1, title: "早朝", beats: [{ time: "早朝", place: "メコン", detail: "散歩。" }] }],
  }),
  intl({
    id: "phnompenh",
    name: "プノンペン",
    country: "カンボジア",
    city: "プノンペン",
    hook: "王宮と、トンレサップ。",
    why: "シェムリアップとセット。",
    weights: { solitude: 0.42, novelty: 0.85, slow: 0.48, nature: 0.28, comfort: 0.48, food: 0.78, rest: 0.42, culture: 0.85 },
    dailyMin: 15000, dailyMax: 32000, minDays: 3, maxDays: 6,
    flightHours: "約6時間30分", airport: "PNH", groundNote: "Grab",
    plan: [{ day: 1, title: "王宮", beats: [{ time: "午前", place: "Royal Palace", detail: "短く。" }] }],
  }),
  intl({
    id: "warsaw",
    name: "ワルシャワ",
    country: "ポーランド",
    city: "ワルシャワ",
    hook: "旧市街の復元。",
    why: "クラクフより、首都。",
    weights: { solitude: 0.48, novelty: 0.8, slow: 0.58, nature: 0.25, comfort: 0.65, food: 0.72, rest: 0.5, culture: 0.85 },
    dailyMin: 26000, dailyMax: 52000, minDays: 3, maxDays: 6,
    flightHours: "約13時間", airport: "WAW", groundNote: "メトロ",
    plan: [{ day: 1, title: "旧市街", beats: [{ time: "午後", place: "広場", detail: "歩く。" }] }],
  }),
  intl({
    id: "edinburgh",
    name: "エディンバラ",
    country: "イギリス",
    city: "エディンバラ",
    hook: "城と、フリンジ。",
    why: "ロンドンより、北。",
    weights: { solitude: 0.5, novelty: 0.82, slow: 0.62, nature: 0.38, comfort: 0.72, food: 0.68, rest: 0.55, culture: 0.88 },
    dailyMin: 36000, dailyMax: 75000, minDays: 3, maxDays: 6,
    flightHours: "約13時間", airport: "EDI", groundNote: "トラム",
    plan: [{ day: 1, title: "ロイヤルマイル", beats: [{ time: "午後", place: "旧市街", detail: "歩く。" }] }],
  }),
  intl({
    id: "dublin",
    name: "ダブリン",
    country: "アイルランド",
    city: "ダブリン",
    hook: "パブと、文学。",
    why: "島国の首都。",
    weights: { solitude: 0.48, novelty: 0.78, slow: 0.58, nature: 0.32, comfort: 0.72, food: 0.75, rest: 0.52, culture: 0.82 },
    dailyMin: 34000, dailyMax: 70000, minDays: 3, maxDays: 6,
    flightHours: "約13時間", airport: "DUB", groundNote: "Luas",
    plan: [{ day: 1, title: "Temple Bar", beats: [{ time: "夜", place: "地区", detail: "短く。" }] }],
  }),
  intl({
    id: "nice",
    name: "ニース",
    country: "フランス",
    city: "ニース",
    hook: "コートダジュール。",
    why: "パリより、海。",
    weights: { solitude: 0.48, novelty: 0.8, slow: 0.68, nature: 0.55, comfort: 0.75, food: 0.82, rest: 0.65, culture: 0.78 },
    dailyMin: 36000, dailyMax: 75000, minDays: 3, maxDays: 6,
    flightHours: "約13時間", airport: "NCE", groundNote: "トラム",
    plan: [{ day: 1, title: "Promenade", beats: [{ time: "夕方", place: "海沿い", detail: "歩く。" }] }],
  }),
  intl({
    id: "sandiego",
    name: "サンディエゴ",
    country: "アメリカ",
    city: "サンディエゴ",
    hook: "国境の近く、海。",
    why: "LAより、穏やか。",
    weights: { solitude: 0.5, novelty: 0.75, slow: 0.58, nature: 0.62, comfort: 0.75, food: 0.78, rest: 0.58, culture: 0.68 },
    dailyMin: 36000, dailyMax: 75000, minDays: 4, maxDays: 7,
    flightHours: "約10時間", airport: "SAN", groundNote: "Uber",
    plan: [{ day: 1, title: "Balboa", beats: [{ time: "午後", place: "公園", detail: "歩く。" }] }],
  }),
  intl({
    id: "dc",
    name: "ワシントンD.C.",
    country: "アメリカ",
    city: "ワシントン",
    hook: "記念碑と、博物館。",
    why: "NYより、整然。",
    weights: { solitude: 0.45, novelty: 0.78, slow: 0.52, nature: 0.35, comfort: 0.72, food: 0.72, rest: 0.48, culture: 0.9 },
    dailyMin: 38000, dailyMax: 78000, minDays: 3, maxDays: 6,
    flightHours: "約13時間", airport: "IAD", groundNote: "Metro",
    plan: [{ day: 1, title: "Mall", beats: [{ time: "午前", place: "国立博物館", detail: "一つ。" }] }],
  }),
  intl({
    id: "telaviv",
    name: "テルアビブ",
    country: "イスラエル",
    city: "テルアビブ",
    hook: "ビーチと、スタートアップ。",
    why: "中東の地中海。",
    weights: { solitude: 0.42, novelty: 0.88, slow: 0.48, nature: 0.45, comfort: 0.72, food: 0.85, rest: 0.52, culture: 0.78 },
    dailyMin: 32000, dailyMax: 68000, minDays: 4, maxDays: 7,
    flightHours: "約12時間", airport: "TLV", groundNote: "鉄道",
    plan: [{ day: 1, title: "旧市街", beats: [{ time: "午後", place: "ヤッファ", detail: "歩く。" }] }],
  }),
  intl({
    id: "fiji",
    name: "フィジー",
    country: "フィジー",
    city: "ナディ",
    hook: "南の島々。",
    why: "タヒチより、近い。",
    weights: { solitude: 0.58, novelty: 0.88, slow: 0.88, nature: 0.92, comfort: 0.72, food: 0.62, rest: 0.9, culture: 0.55 },
    dailyMin: 42000, dailyMax: 88000, minDays: 5, maxDays: 10,
    flightHours: "約9時間", airport: "NAN", groundNote: "ボート",
    plan: [{ day: 1, title: "到着", beats: [{ time: "終日", place: "リゾート", detail: "休む。" }] }],
  }),
  intl({
    id: "saopaulo",
    name: "サンパウロ",
    country: "ブラジル",
    city: "サンパウロ",
    hook: "南米最大の都市。",
    why: "リオより、食。",
    weights: { solitude: 0.35, novelty: 0.88, slow: 0.42, nature: 0.22, comfort: 0.55, food: 0.92, rest: 0.38, culture: 0.78 },
    dailyMin: 26000, dailyMax: 55000, minDays: 4, maxDays: 8,
    flightHours: "約24時間", airport: "GRU", groundNote: "Uber",
    plan: [{ day: 1, title: "Paulista", beats: [{ time: "午後", place: "大通り", detail: "歩く。" }] }],
  }),
  intl({
    id: "johor",
    name: "ジョホールバル",
    country: "マレーシア",
    city: "ジョホールバル",
    hook: "シンガポールの隣。",
    why: "KLより、近場。",
    weights: { solitude: 0.4, novelty: 0.72, slow: 0.45, nature: 0.28, comfort: 0.65, food: 0.88, rest: 0.42, culture: 0.62 },
    dailyMin: 16000, dailyMax: 34000, minDays: 2, maxDays: 5,
    flightHours: "約7時間", airport: "JHB", groundNote: "Grab",
    plan: [{ day: 1, title: "食", beats: [{ time: "夜", place: "ホーカー", detail: "一皿。" }] }],
  }),
];
