import { buildDomesticCatalog, type DomesticSpot } from "./spot-builder";

/** 都道府県代表に加える、第2候補の観光地 */
const SPOTS: DomesticSpot[] = [
  { prefecture: "北海道", name: "小樽", lat: 43.1907, lon: 140.9947, hook: "運河とガラス。港町の余白。", why: "札幌より静かな北海道。", tags: "港 古い町 海" },
  { prefecture: "青森", name: "十和田湖", lat: 40.471, lon: 141.098, hook: "深い湖と、奥入瀬の流れ。", why: "自然の密度が高い北の湖。", tags: "湖 自然 国立公園" },
  { prefecture: "岩手", name: "盛岡", lat: 39.7036, lon: 141.1527, hook: "わんこそばと、城跡。", why: "平泉の前後に置きやすい拠点。", tags: "街 食べ歩き" },
  { prefecture: "宮城", name: "仙台", lat: 38.2682, lon: 140.8694, hook: "杜の都。食と都市のバランス。", why: "松島への入口。", tags: "街 食べ歩き" },
  { prefecture: "秋田", name: "男鹿", lat: 39.902, lon: 139.847, hook: "なまはげと、日本海。", why: "角館より荒い海。", tags: "海 文化 自然" },
  { prefecture: "山形", name: "蔵王", lat: 38.139, lon: 140.441, hook: "樹氷と、温泉。", why: "冬の非日常。", tags: "温泉 山 雪" },
  { prefecture: "福島", name: "猪苗代", lat: 37.559, lon: 140.088, hook: "湖と磐梯山。", why: "会津の自然を短く。", tags: "湖 山 自然" },
  { prefecture: "茨城", name: "大子", lat: 36.757, lon: 140.354, hook: "渓谷と、滝。", why: "日帰り圏の自然。", tags: "渓谷 自然" },
  { prefecture: "栃木", name: "那須", lat: 37.031, lon: 139.989, hook: "高原の空気。", why: "日光より静かな高原。", tags: "高原 自然 温泉" },
  { prefecture: "群馬", name: "伊香保", lat: 36.494, lon: 138.921, hook: "石段と、温泉街。", why: "草津より近場の湯。", tags: "温泉 古い町" },
  { prefecture: "埼玉", name: "川越", lat: 35.925, lon: 139.485, hook: "蔵造りの町並み。", why: "東京から、古い町。", tags: "古い町 歴史" },
  { prefecture: "千葉", name: "铫子", lat: 35.734, lon: 140.826, hook: "犬吠埼と、太平洋。", why: "港の光と、朝。", tags: "海 港 自然" },
  { prefecture: "東京", name: "伊豆大島", lat: 34.741, lon: 139.432, hook: "火山島。東京だけど別世界。", why: "短い日数で、島。", tags: "島 火山 海" },
  { prefecture: "神奈川", name: "箱根", lat: 35.232, lon: 139.106, hook: "湯と、芦ノ湖。", why: "定番の休息。", tags: "温泉 湖 自然" },
  { prefecture: "新潟", name: "新潟", lat: 37.902, lon: 139.023, hook: "日本海と、米。", why: "越後の都市。食が強い。", tags: "街 食べ歩き 海" },
  { prefecture: "富山", name: "雨晴", lat: 36.791, lon: 137.235, hook: "立山連峰が海から見える。", why: "写真より、朝の静けさ。", tags: "海 山 自然" },
  { prefecture: "石川", name: "加賀温泉", lat: 36.314, lon: 136.327, hook: "山中温泉の静けさ。", why: "金沢より湯。", tags: "温泉 休息" },
  { prefecture: "福井", name: "東尋坊", lat: 36.255, lon: 136.108, hook: "断崖の風。", why: "福井の象徴。", tags: "海 断崖 自然" },
  { prefecture: "山梨", name: "富士吉田", lat: 35.487, lon: 138.807, hook: "富士の正面。", why: "河口湖とセットでも単独でも。", tags: "山 自然" },
  { prefecture: "長野", name: "上高地", lat: 36.255, lon: 137.648, hook: "河童橋と、穂高。", why: "歩く自然。宿泊は松本。", tags: "山 自然 国立公園" },
  { prefecture: "岐阜", name: "馬籠宿", lat: 35.529, lon: 137.594, hook: "旧中山道の宿場。", why: "高山と違う、坂の町。", tags: "古い町 歴史" },
  { prefecture: "静岡", name: "伊豆", lat: 34.975, lon: 139.092, hook: "海と温泉の半島。", why: "熱海より広い伊豆。", tags: "温泉 海" },
  { prefecture: "愛知", name: "蒲郡", lat: 34.826, lon: 137.219, hook: "ラグーナと、三河湾。", why: "名古屋から、海。", tags: "海 リゾート" },
  { prefecture: "三重", name: "鳥羽", lat: 34.481, lon: 136.843, hook: "海女と、伊勢神宮の近さ。", why: "伊勢とセット。", tags: "海 食べ歩き" },
  { prefecture: "滋賀", name: "琵琶湖", lat: 35.248, lon: 136.048, hook: "湖の大きさ。", why: "京都の混雑を避ける。", tags: "湖 自然" },
  { prefecture: "京都", name: "嵐山", lat: 35.009, lon: 135.677, hook: "竹林と、渡月橋。", why: "京都の中の、自然。", tags: "自然 寺 歴史" },
  { prefecture: "大阪", name: "堺", lat: 34.573, lon: 135.483, hook: "古墳と、泉州。", why: "大阪の裏側。", tags: "歴史 海" },
  { prefecture: "兵庫", name: "城崎温泉", lat: 35.627, lon: 134.809, hook: "七つの外湯。", why: "神戸より、湯の町。", tags: "温泉 古い町" },
  { prefecture: "奈良", name: "吉野", lat: 34.367, lon: 135.853, hook: "千本桜と、修验道。", why: "奈良平城より、山。", tags: "山 寺 自然" },
  { prefecture: "和歌山", name: "高野山", lat: 34.213, lon: 135.586, hook: "奥之院と、宿坊。", why: "静けさが深い。", tags: "寺 歴史 休息" },
  { prefecture: "鳥取", name: "境港", lat: 35.539, lon: 133.231, hook: "水木しげるの町。", why: "砂丘と違う、港の顔。", tags: "港 街 文化" },
  { prefecture: "島根", name: "石見银山", lat: 35.114, lon: 132.443, hook: "世界遺産の坑道。", why: "出雲より、銀の歴史。", tags: "世界遺産 歴史" },
  { prefecture: "岡山", name: "吉備路", lat: 34.65, lon: 133.933, hook: "岡山後楽園の近さ。", why: "瀬戸内の平野。", tags: "庭園 歴史" },
  { prefecture: "広島", name: "呉", lat: 34.249, lon: 132.566, hook: "軍港と、海。", why: "尾道・宮島と三角。", tags: "港 海 歴史" },
  { prefecture: "山口", name: "下関", lat: 33.957, lon: 130.941, hook: "ふぐと、関門海峡。", why: "本州の西端。", tags: "海 食べ歩き" },
  { prefecture: "徳島", name: "大歩危", lat: 33.875, lon: 133.815, hook: "祖谷のかずら橋。", why: "秘境の定番。", tags: "渓谷 秘境 自然" },
  { prefecture: "香川", name: "琴平", lat: 34.187, lon: 133.821, hook: "金刀比羅宮の階段。", why: "小豆島とセット。", tags: "神社 歴史" },
  { prefecture: "愛媛", name: "松山", lat: 33.839, lon: 132.765, hook: "道後より、城と港。", why: "四国の拠点。", tags: "城 港 街" },
  { prefecture: "高知", name: "桂浜", lat: 33.497, lon: 133.574, hook: "坂本龍馬と、太平洋。", why: "四万十より、海。", tags: "海 歴史" },
  { prefecture: "福岡", name: "柳川", lat: 33.162, lon: 130.406, hook: "掘割の舟下り。", why: "太宰府より、水の町。", tags: "古い町 水" },
  { prefecture: "佐賀", name: "唐津", lat: 33.449, lon: 129.968, hook: "虹の松原と、海。", why: "嬉野と違う、北九州の海。", tags: "海 自然" },
  { prefecture: "長崎", name: "雲仙", lat: 32.75, lon: 130.133, hook: "温泉と、教会。", why: "長崎市より、山。", tags: "温泉 歴史 自然" },
  { prefecture: "熊本", name: "天草", lat: 32.458, lon: 130.193, hook: "離島と、教会。", why: "阿蘇と海、両方。", tags: "島 海 歴史" },
  { prefecture: "大分", name: "日田", lat: 33.321, lon: 130.941, hook: "玖珠川の流れ。", why: "由布院より、町。", tags: "町 川 古い町" },
  { prefecture: "宮崎", name: "青島", lat: 31.803, lon: 131.457, hook: "鬼の洗板と、海。", why: "高千穂より、海。", tags: "海 自然" },
  { prefecture: "鹿児島", name: "指宿", lat: 31.253, lon: 130.633, hook: "砂蒸し温泉。", why: "桜島より、湯。", tags: "温泉 海 休息" },
  { prefecture: "沖縄", name: "宮古島", lat: 24.805, lon: 125.281, hook: "与那覇前浜の青。", why: "那覇より、海。", tags: "島 海 リゾート" },
];

export const prefectureExtraDestinations = buildDomesticCatalog(SPOTS, "pref2");
