import { buildDomesticCatalog, type DomesticSpot } from "./spot-builder";

/** 都道府県代表・第2候補に加える、第3候補の観光地 */
const SPOTS: DomesticSpot[] = [
  { prefecture: "北海道", name: "美瑛", lat: 43.588, lon: 142.467, hook: "パッチワークの丘。", why: "富良野より、静かな丘。", tags: "自然 高原 町" },
  { prefecture: "青森", name: "浅虫温泉", lat: 40.889, lon: 140.857, hook: "津軽の海と、湯。", why: "弘前から、海の温泉。", tags: "温泉 海" },
  { prefecture: "岩手", name: "花巻", lat: 39.388, lon: 141.117, hook: "宮沢賢治の里。", why: "平泉より、文学と湯。", tags: "温泉 文化 町" },
  { prefecture: "宮城", name: "塩竈", lat: 38.315, lon: 141.021, hook: "松島の近く、港の朝。", why: "仙台・松島と三角。", tags: "港 海 神社" },
  { prefecture: "秋田", name: "横手", lat: 39.317, lon: 140.568, hook: "かまくらと、雪。", why: "角館より、雪の祭り。", tags: "雪 町 文化" },
  { prefecture: "山形", name: "酒田", lat: 38.914, lon: 139.836, hook: "羽黒山と、日本海。", why: "银山温泉より、海側。", tags: "海 寺 自然" },
  { prefecture: "福島", name: "いわき", lat: 37.05, lon: 140.888, hook: "小名浜と、太平洋。", why: "会津より、海。", tags: "海 リゾート" },
  { prefecture: "茨城", name: "筑波", lat: 36.203, lon: 140.107, hook: "研究学園と、山。", why: "大洗より、山。", tags: "山 自然" },
  { prefecture: "栃木", name: "宇都宮", lat: 36.556, lon: 139.883, hook: "餃子と、街。", why: "日光の前後に。", tags: "街 食べ歩き" },
  { prefecture: "群馬", name: "榛名湖", lat: 36.447, lon: 139.151, hook: "湖と、榛名山。", why: "草津より、近場の湖。", tags: "湖 山 自然" },
  { prefecture: "埼玉", name: "長瀞", lat: 36.097, lon: 139.115, hook: "岩畳と、川。", why: "秩父より、川下り。", tags: "川 渓谷 自然" },
  { prefecture: "千葉", name: "成田", lat: 35.776, lon: 140.318, hook: "成田山と、空港の近さ。", why: "鴨川より、寺。", tags: "寺 歴史" },
  { prefecture: "東京", name: "神津島", lat: 34.205, lon: 139.134, hook: "東京の島。透ける海。", why: "奥多摩より、本格的な島。", tags: "島 海 自然" },
  { prefecture: "神奈川", name: "横浜", lat: 35.444, lon: 139.638, hook: "港と、中華街。", why: "鎌倉より、都市。", tags: "港 街 夜景" },
  { prefecture: "新潟", name: "弥彦", lat: 37.691, lon: 138.835, hook: "弥彦山と、温泉。", why: "越後湯沢より、神社。", tags: "温泉 神社 山" },
  { prefecture: "富山", name: "五箇山", lat: 36.436, lon: 136.937, hook: "合掌造りの里。", why: "立山より、白川郷の近く。", tags: "世界遺産 古い町" },
  { prefecture: "石川", name: "七尾", lat: 37.043, lon: 136.962, hook: "能登半島の港。", why: "輪島より、港町。", tags: "港 海 食べ歩き" },
  { prefecture: "福井", name: "越前", lat: 35.903, lon: 136.169, hook: "越前海岸と、陶。", why: "東尋坊より、文化。", tags: "海 文化 歴史" },
  { prefecture: "山梨", name: "昇仙峡", lat: 35.788, lon: 138.553, hook: "渓谷の深さ。", why: "河口湖より、歩く自然。", tags: "渓谷 山 自然" },
  { prefecture: "長野", name: "白馬", lat: 36.698, lon: 137.862, hook: "北アルプスの入口。", why: "軽井沢より、山。", tags: "山 自然 雪" },
  { prefecture: "岐阜", name: "郡上", lat: 35.749, lon: 136.964, hook: "八幡の流し。", why: "白川郷より、水の町。", tags: "古い町 川 文化" },
  { prefecture: "静岡", name: "浜松", lat: 34.711, lon: 137.726, hook: "浜名湖と、うなぎ。", why: "熱海より、湖。", tags: "湖 食べ歩き" },
  { prefecture: "愛知", name: "豊橋", lat: 34.769, lon: 137.391, hook: "東三河の入口。", why: "名古屋より、海。", tags: "海 街" },
  { prefecture: "三重", name: "志摩", lat: 34.328, lon: 136.821, hook: "英虞湾と、真珠。", why: "伊勢とセット。", tags: "海 自然" },
  { prefecture: "滋賀", name: "長浜", lat: 35.381, lon: 136.276, hook: "黒壁と、琵琶湖。", why: "彦根と隣。", tags: "古い町 湖 歴史" },
  { prefecture: "京都", name: "天橋立", lat: 35.564, lon: 135.196, hook: "日本三景のひとつ。", why: "京都市内より、海。", tags: "海 自然 世界遺産" },
  { prefecture: "大阪", name: "箕面", lat: 34.826, lon: 135.469, hook: "滝と、もみじ。", why: "大阪の奥、自然。", tags: "渓谷 自然" },
  { prefecture: "兵庫", name: "淡路島", lat: 34.294, lon: 134.775, hook: "島と、たまねぎ。", why: "神戸より、島。", tags: "島 海 自然" },
  { prefecture: "奈良", name: "橿原", lat: 34.509, lon: 135.793, hook: "神武天皇と、古墳。", why: "奈良より、起源。", tags: "歴史 神社" },
  { prefecture: "和歌山", name: "串本", lat: 33.472, lon: 135.783, hook: "本州最南端。", why: "白浜より、海。", tags: "海 自然" },
  { prefecture: "鳥取", name: "大山", lat: 35.362, lon: 133.618, hook: "伯耆富士。", why: "砂丘より、山。", tags: "山 自然" },
  { prefecture: "島根", name: "津和野", lat: 34.467, lon: 131.771, hook: "城下町の坂。", why: "出雲より、町。", tags: "古い町 城 歴史" },
  { prefecture: "岡山", name: "蒜山", lat: 35.254, lon: 133.618, hook: "高原の牧場。", why: "岡山の山側。", tags: "高原 自然" },
  { prefecture: "広島", name: "三次", lat: 34.797, lon: 132.85, hook: "三次のワイナリー。", why: "宮島より、山。", tags: "自然 文化" },
  { prefecture: "山口", name: "角島", lat: 34.312, lon: 130.908, hook: "青い橋と、海。", why: "萩より、絶景。", tags: "海 橋 自然" },
  { prefecture: "徳島", name: "阿波勝浦", lat: 33.932, lon: 134.51, hook: "うだつの町並み。", why: "鳴門より、町。", tags: "古い町 歴史" },
  { prefecture: "香川", name: "高松", lat: 34.34, lon: 134.043, hook: "瀬戸大橋の入口。", why: "小豆島への拠点。", tags: "港 街 海" },
  { prefecture: "愛媛", name: "宇和島", lat: 33.223, lon: 132.566, hook: "城と、真鯛。", why: "道後より、南。", tags: "城 海 食べ歩き" },
  { prefecture: "高知", name: "室戸岬", lat: 33.237, lon: 134.176, hook: "太平洋の突端。", why: "四万十より、岬。", tags: "海 断崖 自然" },
  { prefecture: "福岡", name: "宗像", lat: 33.8, lon: 130.541, hook: "宗像大社と、海。", why: "太宰府より、海。", tags: "神社 海" },
  { prefecture: "佐賀", name: "伊万里", lat: 33.265, lon: 129.88, hook: "伊万里焼と、港。", why: "嬉野より、陶。", tags: "港 文化 歴史" },
  { prefecture: "長崎", name: "五島", lat: 32.695, lon: 128.841, hook: "教会と、離島。", why: "長崎市より、島。", tags: "島 海 歴史" },
  { prefecture: "熊本", name: "球磨", lat: 32.211, lon: 130.755, hook: "人吉と、球磨川。", why: "阿蘇より、川。", tags: "川 温泉 自然" },
  { prefecture: "大分", name: "国見", lat: 33.279, lon: 131.691, hook: "湯布院の隣、静かな湯。", why: "由布院より、穴場。", tags: "温泉 休息" },
  { prefecture: "宮崎", name: "日南", lat: 31.601, lon: 131.378, hook: "モアイと、青い海。", why: "高千穂より、海。", tags: "海 自然" },
  { prefecture: "鹿児島", name: "種子島", lat: 30.412, lon: 130.901, hook: "ロケットと、海。", why: "桜島より、離島。", tags: "島 海 自然" },
  { prefecture: "沖縄", name: "久米島", lat: 26.341, lon: 126.801, hook: "島時間の青。", why: "那覇より、離島。", tags: "島 海 リゾート" },
];

export const prefectureThirdDestinations = buildDomesticCatalog(SPOTS, "pref3");
