import { buildDomesticCatalog, type DomesticSpot } from "./spot-builder";

/** 都道府県第4候補 — さらに穴場・ローカル寄り */
const SPOTS: DomesticSpot[] = [
  { prefecture: "北海道", name: "層雲峡", lat: 43.727, lon: 142.919, hook: "峡谷と、氷瀑。", why: "美瑛より、渓谷。", tags: "渓谷 自然 雪" },
  { prefecture: "青森", name: "五所川原", lat: 40.812, lon: 140.447, hook: "ねぶたの里。", why: "弘前より、祭り。", tags: "文化 町" },
  { prefecture: "岩手", name: "久慈", lat: 40.19, lon: 141.775, hook: "カツオと、太平洋。", why: "平泉より、海。", tags: "海 食べ歩き" },
  { prefecture: "宮城", name: "白石", lat: 38.002, lon: 140.619, hook: "蔵王の近く、城。", why: "仙台より、歴史。", tags: "城 歴史" },
  { prefecture: "秋田", name: "大曲", lat: 39.453, lon: 140.468, hook: "全国花火の町。", why: "田沢湖より、夏。", tags: "文化 町" },
  { prefecture: "山形", name: "米沢", lat: 37.922, lon: 140.117, hook: "牛と、桜。", why: "银山温泉より、街。", tags: "街 食べ歩き" },
  { prefecture: "福島", name: "二本松", lat: 37.585, lon: 140.431, hook: "霞城と、桃。", why: "会津より、城。", tags: "城 歴史" },
  { prefecture: "茨城", name: "水戸", lat: 36.341, lon: 140.447, hook: "偕楽園と、梅。", why: "大洗より、庭園。", tags: "庭園 歴史" },
  { prefecture: "栃木", name: "足利", lat: 36.337, lon: 139.45, hook: "あしかがフラワーパーク。", why: "日光より、花。", tags: "自然 文化" },
  { prefecture: "群馬", name: "桐生", lat: 36.408, lon: 139.333, hook: "織物の町。", why: "草津より、工芸。", tags: "文化 古い町" },
  { prefecture: "埼玉", name: "所沢", lat: 35.799, lon: 139.469, hook: "航空記念公園。", why: "秩父より、近場。", tags: "自然 文化" },
  { prefecture: "千葉", name: "佐原", lat: 35.889, lon: 140.499, hook: "江戸の港町。", why: "鴨川より、歴史。", tags: "港 古い町 歴史" },
  { prefecture: "東京", name: "青梅", lat: 35.787, lon: 139.276, hook: "玉川上水と、梅。", why: "奥多摩より、町。", tags: "古い町 自然" },
  { prefecture: "神奈川", name: "逗子", lat: 35.295, lon: 139.578, hook: "湘南の静かな海。", why: "鎌倉より、海。", tags: "海 リゾート" },
  { prefecture: "新潟", name: "村上", lat: 38.223, lon: 139.478, hook: "鮭と、日本海。", why: "越後湯沢より、海。", tags: "海 食べ歩き" },
  { prefecture: "富山", name: "氷見", lat: 36.856, lon: 137.011, hook: "寒ブリの港。", why: "立山より、海。", tags: "港 海 食べ歩き" },
  { prefecture: "石川", name: "能美", lat: 36.447, lon: 136.553, hook: "陶の里。", why: "金沢より、工芸。", tags: "文化 町" },
  { prefecture: "福井", name: "越前大野", lat: 35.998, lon: 136.165, hook: "天空の城。", why: "東尋坊より、城。", tags: "城 自然" },
  { prefecture: "山梨", name: "韮崎", lat: 35.709, lon: 138.449, hook: "富士の北側。", why: "河口湖より、平野。", tags: "山 自然" },
  { prefecture: "長野", name: "小布施", lat: 36.697, lon: 138.318, hook: "栗と、北斎。", why: "軽井沢より、町。", tags: "町 食べ歩き 文化" },
  { prefecture: "岐阜", name: "多治見", lat: 35.332, lon: 137.132, hook: "美濃焼の町。", why: "高山より、陶。", tags: "文化 町" },
  { prefecture: "静岡", name: "清水", lat: 35.015, lon: 138.489, hook: "富士の正面、港。", why: "熱海より、港。", tags: "港 海 山" },
  { prefecture: "愛知", name: "岡崎", lat: 34.954, lon: 137.174, hook: "徳川生誕の城。", why: "名古屋より、歴史。", tags: "城 歴史" },
  { prefecture: "三重", name: "四日市", lat: 34.965, lon: 136.624, hook: "近畿の工業港。", why: "伊勢より、都市。", tags: "港 街" },
  { prefecture: "滋賀", name: "大津", lat: 35.004, lon: 135.868, hook: "琵琶湖の南。", why: "彦根と対。", tags: "湖 街" },
  { prefecture: "京都", name: "丹後", lat: 35.674, lon: 135.049, hook: "海の京都。", why: "京都市内より、海。", tags: "海 自然" },
  { prefecture: "大阪", name: "岸和田", lat: 34.463, lon: 135.371, hook: "だんじりの町。", why: "大阪より、南。", tags: "文化 海" },
  { prefecture: "兵庫", name: "赤穂", lat: 34.755, lon: 134.391, hook: "忠臣蔵の塩。", why: "神戸より、歴史。", tags: "歴史 海" },
  { prefecture: "奈良", name: "大和路", lat: 34.685, lon: 135.805, hook: "古の都を横断。", why: "奈良より、広い。", tags: "歴史 自然" },
  { prefecture: "和歌山", name: "田辺", lat: 33.727, lon: 135.377, hook: "熊野への入口。", why: "白浜より、山。", tags: "自然 歴史" },
  { prefecture: "鳥取", name: "倉吉", lat: 35.43, lon: 133.825, hook: "白壁の町。", why: "砂丘より、町。", tags: "古い町 歴史" },
  { prefecture: "島根", name: "益田", lat: 34.668, lon: 131.843, hook: "西部の港。", why: "出雲より、海。", tags: "港 海" },
  { prefecture: "岡山", name: "総社", lat: 34.672, lon: 133.936, hook: "吉備路の平野。", why: "岡山より、歴史。", tags: "歴史 町" },
  { prefecture: "広島", name: "福山", lat: 34.485, lon: 133.362, hook: "鞆の浦の隣。", why: "宮島より、港。", tags: "港 歴史" },
  { prefecture: "山口", name: "防府", lat: 34.052, lon: 131.568, hook: "防府天満宮。", why: "萩より、神社。", tags: "神社 歴史" },
  { prefecture: "徳島", name: "美馬", lat: 34.052, lon: 134.151, hook: "藍の里。", why: "鳴門より、文化。", tags: "文化 歴史" },
  { prefecture: "香川", name: "観音寺", lat: 34.125, lon: 133.662, hook: "父母ヶ浜の近く。", why: "小豆島より、海。", tags: "海 自然" },
  { prefecture: "愛媛", name: "大洲", lat: 33.506, lon: 132.544, hook: "城と、肱川。", why: "道後より、城。", tags: "城 川 歴史" },
  { prefecture: "高知", name: "須崎", lat: 33.401, lon: 133.282, hook: "土佐湾の港。", why: "四万十より、港。", tags: "港 海" },
  { prefecture: "福岡", name: "久留米", lat: 33.319, lon: 130.508, hook: "うどんと、筑後川。", why: "太宰府より、町。", tags: "街 食べ歩き" },
  { prefecture: "佐賀", name: "有田", lat: 33.188, lon: 129.899, hook: "有田焼の里。", why: "嬉野より、陶。", tags: "文化 歴史" },
  { prefecture: "長崎", name: "佐世保", lat: 33.18, lon: 129.711, hook: "ハンバーガーと、港。", why: "長崎市より、海。", tags: "港 海 食べ歩き" },
  { prefecture: "熊本", name: "八代", lat: 32.507, lon: 130.601, hook: "八代海の夕日。", why: "阿蘇より、海。", tags: "海 自然" },
  { prefecture: "大分", name: "中津", lat: 33.598, lon: 131.188, hook: "城と、もつ鍋。", why: "由布院より、城。", tags: "城 食べ歩き" },
  { prefecture: "宮崎", name: "延岡", lat: 32.582, lon: 131.665, hook: "日向灘。", why: "高千穂より、海。", tags: "海 自然" },
  { prefecture: "鹿児島", name: "霧島", lat: 31.934, lon: 130.856, hook: "温泉と、神話。", why: "桜島より、山。", tags: "温泉 山 自然" },
  { prefecture: "沖縄", name: "名護", lat: 26.592, lon: 127.977, hook: "本部町の近く、海。", why: "那覇より、北。", tags: "海 自然" },
];

export const prefectureFourthDestinations = buildDomesticCatalog(SPOTS, "pref4");
