import { buildDomesticCatalog, type DomesticSpot } from "./spot-builder";

/** 都道府県第5候補 — ローカル・ニッチ寄り */
const SPOTS: DomesticSpot[] = [
  { prefecture: "北海道", name: "紋別", lat: 44.356, lon: 143.355, hook: "オホーツクの流氷。", why: "知床より、鄂霍次克。", tags: "海 自然 雪" },
  { prefecture: "青森", name: "むつ", lat: 41.293, lon: 141.183, hook: "下北半島の突端。", why: "本州最北。", tags: "海 自然 秘境" },
  { prefecture: "岩手", name: "一関", lat: 38.934, lon: 141.126, hook: "厳美渓と、川。", why: "平泉の隣。", tags: "渓谷 自然" },
  { prefecture: "宮城", name: "石巻", lat: 38.434, lon: 141.303, hook: "牡鹿半島の入口。", why: "松島より、港。", tags: "港 海" },
  { prefecture: "秋田", name: "能代", lat: 40.213, lon: 140.026, hook: "火の祭り。", why: "田沢湖より、海。", tags: "海 文化" },
  { prefecture: "山形", name: "尾花沢", lat: 38.6, lon: 140.406, hook: "さくらんぼの里。", why: "银山温泉より、田園。", tags: "自然 町" },
  { prefecture: "福島", name: "相馬", lat: 37.797, lon: 140.967, hook: "相馬野馬追。", why: "太平洋側。", tags: "海 文化 歴史" },
  { prefecture: "茨城", name: "北茨城", lat: 36.806, lon: 140.751, hook: "大洗より、北。", why: "海と、町。", tags: "海 町" },
  { prefecture: "栃木", name: "真岡", lat: 36.441, lon: 140.014, hook: "真岡鐵道。", why: "日光より、田園。", tags: "町 自然" },
  { prefecture: "群馬", name: "沼田", lat: 36.646, lon: 139.044, hook: "利根川の源流。", why: "草津より、川。", tags: "川 自然" },
  { prefecture: "埼玉", name: "越生", lat: 35.966, lon: 139.3, hook: "麦の秋。", why: "秩父の近く。", tags: "自然 町" },
  { prefecture: "千葉", name: "館山", lat: 34.996, lon: 139.87, hook: "南房総の入口。", why: "鴨川より、南。", tags: "海 自然" },
  { prefecture: "東京", name: "檜原", lat: 35.726, lon: 139.149, hook: "都内最後の秘境。", why: "奥多摩より、深い。", tags: "山 自然 秘境" },
  { prefecture: "神奈川", name: "厚木", lat: 35.443, lon: 139.362, hook: "あつぎ鮎。", why: "湘南の奥。", tags: "川 食べ歩き" },
  { prefecture: "新潟", name: "糸魚川", lat: 37.039, lon: 137.862, hook: "日本海と、翡翠。", why: "越後の西。", tags: "海 自然" },
  { prefecture: "富山", name: "砺波", lat: 36.648, lon: 136.959, hook: "チューリップ。", why: "立山より、平野。", tags: "自然 文化" },
  { prefecture: "石川", name: "羽咋", lat: 36.895, lon: 136.779, hook: "能登の入口。", why: "輪島より、海。", tags: "海 自然" },
  { prefecture: "福井", name: "若狭町", lat: 35.542, lon: 135.899, hook: "三方五湖の近く。", why: "東尋坊より、湖。", tags: "湖 自然" },
  { prefecture: "山梨", name: "都留", lat: 35.551, lon: 138.906, hook: "相模湖の近く。", why: "河口湖より、町。", tags: "湖 町" },
  { prefecture: "長野", name: "木曽福島", lat: 35.842, lon: 137.691, hook: "木曽路の宿。", why: "馬籠より、深い。", tags: "古い町 歴史" },
  { prefecture: "岐阜", name: "中津川", lat: 35.683, lon: 137.499, hook: "恵那峡の近く。", why: "高山より、南。", tags: "渓谷 自然" },
  { prefecture: "静岡", name: "焼津", lat: 34.867, lon: 138.323, hook: "カツオの港。", why: "清水より、漁港。", tags: "港 海 食べ歩き" },
  { prefecture: "愛知", name: "田原", lat: 34.668, lon: 137.264, hook: "三河湾の南端。", why: "渥美と同じ半島。", tags: "海 自然" },
  { prefecture: "三重", name: "熊野", lat: 33.888, lon: 136.099, hook: "熊野古道の核心。", why: "伊勢と対。", tags: "世界遺産 歴史 自然" },
  { prefecture: "滋賀", name: "余呉", lat: 35.462, lon: 136.038, hook: "湖西の静けさ。", why: "琵琶湖より、西。", tags: "湖 自然" },
  { prefecture: "京都", name: "舞鶴", lat: 35.474, lon: 135.386, hook: "赤レンガと、港。", why: "丹後より、港。", tags: "港 歴史" },
  { prefecture: "大阪", name: "高槻", lat: 34.851, lon: 135.617, hook: "安満遺跡。", why: "大阪より、北。", tags: "歴史 町" },
  { prefecture: "兵庫", name: "豊岡", lat: 35.544, lon: 134.82, hook: "コウノトリの里。", why: "但馬の中心。", tags: "自然 文化" },
  { prefecture: "奈良", name: "十津川", lat: 33.987, lon: 135.785, hook: "日本一の秘湯郷。", why: "吉野より、奥。", tags: "温泉 秘境 自然" },
  { prefecture: "和歌山", name: "新宮", lat: 33.725, lon: 135.994, hook: "熊野速玉大社。", why: "熊野の入口。", tags: "神社 歴史" },
  { prefecture: "鳥取", name: "日野", lat: 35.243, lon: 133.381, hook: "大山のふもと。", why: "砂丘より、山。", tags: "山 自然" },
  { prefecture: "島根", name: "浜田", lat: 34.899, lon: 132.082, hook: "石見の港。", why: "益田より、海。", tags: "港 海" },
  { prefecture: "岡山", name: "新見", lat: 34.991, lon: 133.473, hook: "蒜山への入口。", why: "岡山より、山。", tags: "自然 高原" },
  { prefecture: "広島", name: "大竹", lat: 34.238, lon: 132.222, hook: "瀬戸内の島々。", why: "宮島より、西。", tags: "海 自然" },
  { prefecture: "山口", name: "柳井", lat: 33.963, lon: 132.102, hook: "白壁の港。", why: "萩より、南。", tags: "港 古い町 海" },
  { prefecture: "徳島", name: "三好", lat: 34.026, lon: 133.806, hook: "吉野川の源流。", why: "大歩危より、奥。", tags: "川 自然 秘境" },
  { prefecture: "香川", name: "さぬき", lat: 34.325, lon: 134.043, hook: "うどんの本場。", why: "高松より、食。", tags: "食べ歩き 町" },
  { prefecture: "愛媛", name: "新居浜", lat: 33.96, lon: 133.283, hook: "銅山の歴史。", why: "松山より、工業港。", tags: "港 歴史" },
  { prefecture: "高知", name: "芸西", lat: 33.526, lon: 133.645, hook: "土佐湾の東。", why: "高知より、海。", tags: "海 自然" },
  { prefecture: "福岡", name: "筑後", lat: 33.211, lon: 130.502, hook: "筑後川の平野。", why: "久留米より、田園。", tags: "川 自然" },
  { prefecture: "佐賀", name: "鳥栖", lat: 33.379, lon: 130.507, hook: "九州のクロスロード。", why: "嬉野より、交通。", tags: "街" },
  { prefecture: "長崎", name: "対馬", lat: 34.202, lon: 129.287, hook: "韓国が近い島。", why: "長崎より、離島。", tags: "島 海 自然" },
  { prefecture: "熊本", name: "菊池", lat: 32.978, lon: 130.815, hook: "菊池渓谷。", why: "阿蘇より、渓谷。", tags: "渓谷 温泉 自然" },
  { prefecture: "大分", name: "宇佐", lat: 33.279, lon: 131.353, hook: "宇佐神宮。", why: "由布院より、神社。", tags: "神社 歴史" },
  { prefecture: "宮崎", name: "えびの", lat: 32.044, lon: 130.813, hook: "霧島連山。", why: "高千穂より、山。", tags: "山 自然" },
  { prefecture: "鹿児島", name: "枕崎", lat: 31.272, lon: 130.297, hook: "本州最南端より、西。", why: "薩摩半島の先。", tags: "海 自然" },
  { prefecture: "沖縄", name: "西表", lat: 24.449, lon: 123.802, hook: "亜熱帯の森。", why: "石垣より、自然。", tags: "島 自然 世界遺産" },
];

export const prefectureFifthDestinations = buildDomesticCatalog(SPOTS, "pref5");
